### ISSUE TITLE
CLI panic'd rudely when I just wanted to tail some logs

### ISSUE THREAD

**Issue by younata** [cloudfoundry/cli#1065]
Now this is a story all about how
My life got flipped-turned upside down
And I'd like to take a minute
Just sit right there
I'll tell you how I got a cli panic extraordinaire

While pairing with @tjarratt, on the fifth floor
on the workstation was where I spent most of my days
Chillin out' maxin' testin' all cool
And all troubleshooting some issues outside of the Vestibule
When a couple of panics, that were up to no good
started making trouble in my neighborhood
I got in one little crash and my pair got scared
He said "You're going to github to file an issue or I'll be despaired"

## Command:

`cf logs my-fancy-app`

## CLI Version:

`cf version 6.21.0+dff2cf8-2016-07-27`

## What occurred
```
± |just-pretend-this-is-a-good-feature-branch {2} S:1 U:1 ✗| → cf logs my-fancy-app
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0xfb2b]

runtime stack:
runtime.throw(0xafe320, 0x2a)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0xf81020)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0xf81020, 0x6, 0x100000000, 0xf83e80)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbff580)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0xf81020, 0x6, 0x10100000000, 0x154dc)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0xb000, 0x0, 0x3f)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xf7c100)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc820055b48 sp=0xc820055b40
runtime.mallocgc(0xb000, 0x90c9c0, 0xc800000000, 0x2b48)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:665 +0x9eb fp=0xc820055c20 sp=0xc820055b48
runtime.newarray(0x90c9c0, 0x100, 0x4)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:798 +0xc9 fp=0xc820055c60 sp=0xc820055c20
runtime.hashGrow(0x779c80, 0xc8200d1590)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/hashmap.go:809 +0x82 fp=0xc820055c90 sp=0xc820055c60
runtime.mapassign1(0x779c80, 0xc8200d1590, 0xbf3320, 0xbf3330)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/hashmap.go:509 +0x5d2 fp=0xc820055d38 sp=0xc820055c90
html.init()
	/usr/local/Cellar/go/1.6.3/libexec/src/html/entity.go:2154 +0xe8 fp=0xc820055da0 sp=0xc820055d38
html/template.init()
	/usr/local/Cellar/go/1.6.3/libexec/src/html/template/url.go:105 +0x70 fp=0xc820055ea0 sp=0xc820055da0
net/rpc.init()
	/usr/local/Cellar/go/1.6.3/libexec/src/net/rpc/server.go:712 +0x6f fp=0xc820055f08 sp=0xc820055ea0
github.com/cloudfoundry/cli/plugin.init()
	/Users/cffadmin/concourse-work-dir/containers/0000118epc9/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/plugin/plugin_shim.go:44 +0x45 fp=0xc820055f10 sp=0xc820055f08
github.com/cloudfoundry/cli/cf/configuration/pluginconfig.init()
	/Users/cffadmin/concourse-work-dir/containers/0000118epc9/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/configuration/pluginconfig/plugin_data.go:31 +0x4a fp=0xc820055f18 sp=0xc820055f10
github.com/cloudfoundry/cli/cf/commandregistry.init()
	/Users/cffadmin/concourse-work-dir/containers/0000118epc9/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/commandregistry/registry.go:175 +0x9c fp=0xc820055f30 sp=0xc820055f18
github.com/cloudfoundry/cli/cf/cmd.init()
	/Users/cffadmin/concourse-work-dir/containers/0000118epc9/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/cmd/writer_unix.go:7 +0x60 fp=0xc820055f48 sp=0xc820055f30
main.init()
	/Users/cffadmin/concourse-work-dir/containers/0000118epc9/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/main.go:12 +0x40 fp=0xc820055f50 sp=0xc820055f48
runtime.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:177 +0x27f fp=0xc820055fa0 sp=0xc820055f50
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820055fa8 sp=0xc820055fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by dkoper** [comment]
WIIIIIIILLLLLLLLLLLLL!!!
you try the latest cf CLI version?

**Comment by dkoper** [comment]
Closing. cf version 6.21.0 is over 6 months old. We build with a different golang version now. Please reopen or submit a new issue if this reoccurs with the latest cf CLI release.
