### ISSUE TITLE
java.util.zip.ZipException: zip file is empty while using dependency jar as environment variables

### ISSUE THREAD

**Issue by amitrajbaral** [cloudfoundry/cli#1086]
I am deploying some application in cloudfoundry. I have some library jar and configuration files also inside the application. I want to setup those jar and config file as environment variable, so I did

`cf set-env APP_NAME JAVA_OPTS "-Dconf=/location/library.jar"` and also tried to setup environment variables using manifest.yml
After these changes, I have to restage the application and I am always getting
 _ERR java.util.zip.ZipException : zip file is empty._

**Comment by donskander2** [comment]
java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:145)
	at com.android.signapk.SignApk.main(SignApk.java:320)
i need help
