### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by anacrolix** [cloudfoundry/cli#1113]
Only occurred once, afaict.

```
$ cf restage my-app
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x481f11f0cc36 pc=0xfb2b]

runtime stack:
runtime.throw(0xafe400, 0x2a)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0xf80220)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).allocStack(0xf80220, 0x4, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:529 +0xc8
runtime.stackpoolalloc(0xf98c00, 0x15)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/stack.go:190 +0x65
runtime.stackcacherefill(0x1113000, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/stack.go:268 +0x59
runtime.stackalloc(0x800, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/stack.go:367 +0x1b0
runtime.malg.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:2641 +0x2b
runtime.systemstack(0x7fff5fbff690)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.malg(0xc800000800, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:2642 +0x73
runtime.newproc1(0xbc4fe8, 0xc8201331b0, 0x8, 0x644e92, 0xc8201331e0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:2691 +0xe4
runtime.newproc.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:2661 +0x48
runtime.systemstack(0xf7b300)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc820133158 sp=0xc820133150
runtime.newproc(0x8, 0xbc4fe8)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:2662 +0x62 fp=0xc8201331a0 sp=0xc820133158
text/template/parse.lex(0xc8202722a0, 0x55, 0xc8202722a0, 0x55, 0x9f3768, 0x2, 0x9f37a8, 0x2, 0x11942)
	/usr/local/Cellar/go/1.6.3/libexec/src/text/template/parse/lex.go:216 +0x162 fp=0xc8201331d8 sp=0xc8201331a0
text/template/parse.(*Tree).Parse(0xc8203ddea0, 0xc8202722a0, 0x55, 0x0, 0x0, 0x0, 0x0, 0xc8203f9b90, 0xc8203db400, 0x2, ...)
	/usr/local/Cellar/go/1.6.3/libexec/src/text/template/parse/parse.go:232 +0x136 fp=0xc820133268 sp=0xc8201331d8
text/template/parse.Parse(0xc8202722a0, 0x55, 0xc8202722a0, 0x55, 0x0, 0x0, 0x0, 0x0, 0xc8203db400, 0x2, ...)
	/usr/local/Cellar/go/1.6.3/libexec/src/text/template/parse/parse.go:55 +0x14c fp=0xc8201332e8 sp=0xc820133268
text/template.(*Template).Parse(0xc8203f4880, 0xc8202722a0, 0x55, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/text/template/template.go:190 +0x2ab fp=0xc820133420 sp=0xc8201332e8
github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n/translation.(*template).parseTemplate(0xc8203f1000, 0xc8202722a0, 0x55, 0x0, 0x0)
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n/translation/template.go:55 +0x261 fp=0xc820133488 sp=0xc820133420
github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n/translation.newTemplate(0xc8202722a0, 0x55, 0xc820276070, 0x0, 0x0)
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n/translation/template.go:17 +0x56 fp=0xc8201334c0 sp=0xc820133488
github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n/translation.NewTranslation(0xc82026e8a0, 0x0, 0x0, 0x0, 0x0)
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n/translation/translation.go:43 +0xc2a fp=0xc8201338c0 sp=0xc8201334c0
github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n/bundle.parseTranslations(0xabc1c0, 0x20, 0xc820188000, 0x2ef2e, 0x3fe00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n/bundle/bundle.go:98 +0x283 fp=0xc820133a58 sp=0xc8201338c0
github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n/bundle.(*Bundle).ParseTranslationFileBytes(0xc820010990, 0xabc1c0, 0x20, 0xc820188000, 0x2ef2e, 0x3fe00, 0x0, 0x0)
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n/bundle/bundle.go:70 +0x3dd fp=0xc820133b80 sp=0xc820133a58
github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n.ParseTranslationFileBytes(0xabc1c0, 0x20, 0xc820188000, 0x2ef2e, 0x3fe00, 0x0, 0x0)
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n/i18n.go:108 +0x61 fp=0xc820133bc8 sp=0xc820133b80
github.com/cloudfoundry/cli/cf/i18n.loadAsset(0xabc1c0, 0x20)
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/i18n/i18n.go:82 +0x2a0 fp=0xc820133ca8 sp=0xc820133bc8
github.com/cloudfoundry/cli/cf/i18n.Init(0x1168218, 0xc820136000, 0xc820136000)
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/i18n/i18n.go:33 +0x3b fp=0xc820133ea0 sp=0xc820133ca8
github.com/cloudfoundry/cli/cf/commandregistry.initI18nFunc(0x1163028)
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/commandregistry/registry.go:34 +0xd2 fp=0xc820133f08 sp=0xc820133ea0
github.com/cloudfoundry/cli/cf/commandregistry.init()
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/commandregistry/registry.go:18 +0xd3 fp=0xc820133f20 sp=0xc820133f08
github.com/cloudfoundry/cli/cf/cmd.init()
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/cf/cmd/writer_unix.go:7 +0x60 fp=0xc820133f38 sp=0xc820133f20
main.init()
	/Users/cffadmin/concourse-work-dir/containers/0000118epdt/tmp/build/254d4083/gopath/src/github.com/cloudfoundry/cli/main.go:12 +0x40 fp=0xc820133f40 sp=0xc820133f38
runtime.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:177 +0x27f fp=0xc820133f90 sp=0xc820133f40
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820133f98 sp=0xc820133f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:28 +0x37

$ cf -v
cf version 6.21.1+6fd3c9f-2016-08-10
```

**Comment by dkoper** [comment]
Hi @anacrolix 

This could possibly be due to https://github.com/golang/go/issues/16331, which has been fixed since.
You are using a cf CLI release that's 6 months old. We've released a number of updates since, built with later Golang versions.
If you see this trace again on the latest release, we will investigate deeper.

Regards,
Dies Koper
CF CLI PM
