### ISSUE TITLE
CTRL+C makes the CLI exit before a plugin can run cleanup tasks

### ISSUE THREAD

**Issue by 46bit** [cloudfoundry/cli#1373]
## Command  

`cf conduit example-postgres` followed by a `CTRL+C`

## What occurred

The CF CLI process received the `SIGINT` and exited immediately. Our [Conduit plugin](https://github.com/alphagov/paas-cf-conduit) received the `SIGINT` and started to delete its CF resources before exiting, but the CF CLI's RPC server is no longer running.

## What you expected to occur

We expected the CF CLI to wait for our plugin to terminate before exiting.

## What impact this has

This makes it harder for plugins to clear up after themselves. Our plugin cannot count on the CF CLI's RPC server running when it cleans up after a `CTRL+C`. This means we duplicate a lot of code.

## CLI Version  

Current master.

## Platform & Shell Details  

Mac OS X 10.11 iTerm

## Any other relevant information  

We're proposing a PR for this shortly.

**Comment by XenoPhex** [comment]
Merged your pull request, thanks for the fix! It'll be in the next version of the CF CLI.

**Comment by XenoPhex** [comment]
:sob: 

I've had to revert this commit due to segfaults in our pipeline. While hard to trigger by hand - it appears that this change causes the plugin interface to error in an extremely unexpected way. (I'll post the segfault below). For now reverting is the safest solution.

Integration test log:
```
[1525460363] Plugin Suite - 140 specs - 16 nodes •••
------------------------------

CMD> cf api https://api.tartine.cli.fun --skip-ssl-validation 
OUT: Setting api endpoint to https://api.tartine.cli.fun...
OUT: OK
OUT: 
OUT: api endpoint:   https://api.tartine.cli.fun
OUT: api version:    2.107.0
OUT: Not logged in. Use 'cf login' to log in.

CMD> cf auth admin u4a5sqn0km8nblhmsek5 
OUT: API endpoint: https://api.tartine.cli.fun
OUT: Authenticating...
OUT: OK
OUT: Use 'cf target' to view or set your target org and space.

CMD> cf remove-plugin-repo CF-Community 
OUT: 
OUT: OK
OUT: CF-Community removed from list of repositories
OUT: 

CMD> cf install-plugin -f /tmp/gexec_artifacts797859608/g389912983/test_plugin 
OUT: Attention: Plugins are binaries written by potentially untrusted authors.
OUT: Install and use plugins at your own risk.
OUT: Installing plugin CF-CLI-Integration-Test-Plugin...
OUT: OK
OUT: Plugin CF-CLI-Integration-Test-Plugin 1.2.4 successfully installed.

CMD> cf Sleep 3000 
==============================Global After Each==============================

• Failure [6.339 seconds]
running plugins signal handling will wait for the plugin to terminate [It] when SIGINT 
/tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

  No future change is possible.  Bailing out early after 0.030s.
  Got stuck at:
      
  Waiting for:
      Slept for 3000 ms

  /tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/integration/plugin/runner_test.go:88
------------------------------
•••••
------------------------------

CMD> cf api https://api.tartine.cli.fun --skip-ssl-validation 
OUT: Setting api endpoint to https://api.tartine.cli.fun...
OUT: OK
OUT: 
OUT: api endpoint:   https://api.tartine.cli.fun
OUT: api version:    2.107.0
OUT: Not logged in. Use 'cf login' to log in.

CMD> cf auth admin u4a5sqn0km8nblhmsek5 
OUT: API endpoint: https://api.tartine.cli.fun
OUT: Authenticating...
OUT: OK
OUT: Use 'cf target' to view or set your target org and space.

CMD> cf remove-plugin-repo CF-Community 
OUT: 
OUT: OK
OUT: CF-Community removed from list of repositories
OUT: 

CMD> cf install-plugin -f /tmp/gexec_artifacts797859608/g389912983/test_plugin 
OUT: Attention: Plugins are binaries written by potentially untrusted authors.
OUT: Install and use plugins at your own risk.
OUT: Installing plugin CF-CLI-Integration-Test-Plugin...
OUT: OK
OUT: Plugin CF-CLI-Integration-Test-Plugin 1.2.4 successfully installed.

CMD> cf Sleep 3000 
==============================Global After Each==============================

• Failure [7.282 seconds]
running plugins signal handling will wait for the plugin to terminate [It] when SIGINT 
/tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

  No future change is possible.  Bailing out early after 0.010s.
  Got stuck at:
      
  Waiting for:
      Slept for 3000 ms

  /tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/integration/plugin/runner_test.go:88
------------------------------
•••••••••••••••••••••••••••••••••••••••••••••••••••••
------------------------------
• [SLOW TEST:75.290 seconds]
install-plugin command installing a plugin from a local file when the file is compiled for a different os and architecture fails and reports the file is not a valid CLI plugin 
/tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/integration/plugin/install_plugin_command_test.go:103
------------------------------
••••
------------------------------

CMD> cf api https://api.tartine.cli.fun --skip-ssl-validation 
OUT: Setting api endpoint to https://api.tartine.cli.fun...
OUT: OK
OUT: 
OUT: api endpoint:   https://api.tartine.cli.fun
OUT: api version:    2.107.0
OUT: Not logged in. Use 'cf login' to log in.

CMD> cf auth admin u4a5sqn0km8nblhmsek5 
OUT: API endpoint: https://api.tartine.cli.fun
OUT: Authenticating...
OUT: OK
OUT: Use 'cf target' to view or set your target org and space.

CMD> cf remove-plugin-repo CF-Community 
OUT: 
OUT: OK
OUT: CF-Community removed from list of repositories
OUT: 

CMD> cf install-plugin -f /tmp/gexec_artifacts834221273/g280213092/test_plugin 
OUT: Attention: Plugins are binaries written by potentially untrusted authors.
OUT: Install and use plugins at your own risk.
OUT: Installing plugin CF-CLI-Integration-Test-Plugin...
OUT: OK
OUT: Plugin CF-CLI-Integration-Test-Plugin 1.2.4 successfully installed.

CMD> cf Sleep 3000 
ERR: SIGQUIT: quit
ERR: PC=0x40fbeb m=0 sigcode=0
ERR: 
ERR: goroutine 1 [running, locked to thread]:
ERR: runtime.mallocgc(0x30, 0xd9b820, 0xc4203cb301, 0x101)
ERR: 	/usr/local/go/src/runtime/malloc.go:785 +0x35b fp=0xc420093590 sp=0xc4200934f0 pc=0x40fbeb
ERR: runtime.newobject(0xd9b820, 0xc4200938b8)
ERR: 	/usr/local/go/src/runtime/malloc.go:839 +0x38 fp=0xc4200935c0 sp=0xc420093590 pc=0x4103d8
ERR: text/template/parse.(*Tree).newList(...)
ERR: 	/usr/local/go/src/text/template/parse/node.go:85
ERR: text/template/parse.(*Tree).parse(0xc4204cb000)
ERR: 	/usr/local/go/src/text/template/parse/parse.go:280 +0xf8 fp=0xc4200938f0 sp=0xc4200935c0 pc=0x5114a8
ERR: text/template/parse.(*Tree).Parse(0xc4204cb000, 0xc4203d03c0, 0x16, 0x0, 0x0, 0x0, 0x0, 0xc4204c7e00, 0xc4203cb320, 0x2, ...)
ERR: 	/usr/local/go/src/text/template/parse/parse.go:233 +0x226 fp=0xc420093968 sp=0xc4200938f0 pc=0x510df6
ERR: text/template/parse.Parse(0xe1031f, 0xc, 0xc4203d03c0, 0x16, 0x0, 0x0, 0x0, 0x0, 0xc4203cb320, 0x2, ...)
ERR: 	/usr/local/go/src/text/template/parse/parse.go:55 +0x108 fp=0xc4200939f0 sp=0xc420093968 pc=0x50fb68
ERR: text/template.(*Template).Parse(0xc4204a1a80, 0xc4203d03c0, 0x16, 0x16, 0xc4204329e8, 0x2872615536ea43df)
ERR: 	/usr/local/go/src/text/template/template.go:198 +0x118 fp=0xc420093af8 sp=0xc4200939f0 pc=0x530eb8
ERR: code.cloudfoundry.org/cli/util/ui.generateTranslationFunc.func1(0xe19f2a, 0x16, 0x0, 0x0, 0x0, 0xc4201ba5c8, 0x8)
ERR: 	/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/ui/i18n.go:118 +0x129 fp=0xc420093b80 sp=0xc420093af8 pc=0x7902c9
ERR: code.cloudfoundry.org/cli/cf/commands/spacequota.(*UpdateSpaceQuota).MetaData(0xc4204c7920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
ERR: 	/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/commands/spacequota/update_space_quota.go:35 +0x3ad fp=0xc420093de0 sp=0xc420093b80 pc=0xa5b43d
ERR: code.cloudfoundry.org/cli/cf/commandregistry.Register(0xeea500, 0xc4204c7920)
ERR: 	/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/commandregistry/registry.go:58 +0x4c fp=0xc420093f08 sp=0xc420093de0 pc=0x90c34c
ERR: code.cloudfoundry.org/cli/cf/commands/spacequota.init.6()
ERR: 	/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/commands/spacequota/update_space_quota.go:27 +0x3d fp=0xc420093f28 sp=0xc420093f08 pc=0xa5b07d
ERR: code.cloudfoundry.org/cli/cf/commands/spacequota.init()
ERR: 	<autogenerated>:1 +0xb6 fp=0xc420093f38 sp=0xc420093f28 pc=0xa5d9e6
ERR: code.cloudfoundry.org/cli/cf/commandsloader.init()
ERR: 	<autogenerated>:1 +0xa7 fp=0xc420093f48 sp=0xc420093f38 pc=0xa5e6f7
ERR: code.cloudfoundry.org/cli/cf/cmd.init()
ERR: 	<autogenerated>:1 +0x66 fp=0xc420093f58 sp=0xc420093f48 pc=0xa68146
ERR: main.init()
ERR: 	<autogenerated>:1 +0x5f fp=0xc420093f88 sp=0xc420093f58 pc=0xbfa30f
ERR: runtime.main()
ERR: 	/usr/local/go/src/runtime/proc.go:186 +0x1ca fp=0xc420093fe0 sp=0xc420093f88 pc=0x42ac8a
ERR: runtime.goexit()
ERR: 	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420093fe8 sp=0xc420093fe0 pc=0x455be1
ERR: 
ERR: goroutine 18 [syscall]:
ERR: os/signal.signal_recv(0x0)
ERR: 	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
ERR: os/signal.loop()
ERR: 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
ERR: created by os/signal.init.0
ERR: 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
ERR: 
ERR: goroutine 617 [chan send]:
ERR: text/template/parse.(*lexer).emit(0xc4204ce0e0, 0x6)
ERR: 	/usr/local/go/src/text/template/parse/lex.go:154 +0xae
ERR: text/template/parse.lexText(0xc4204ce0e0, 0xe51ce8)
ERR: 	/usr/local/go/src/text/template/parse/lex.go:266 +0x1dc
ERR: text/template/parse.(*lexer).run(0xc4204ce0e0)
ERR: 	/usr/local/go/src/text/template/parse/lex.go:228 +0x37
ERR: created by text/template/parse.lex
ERR: 	/usr/local/go/src/text/template/parse/lex.go:221 +0x15f
ERR: 
ERR: rax    0x80000
ERR: rbx    0x0
ERR: rcx    0xc420000180
ERR: rdx    0x1
ERR: rdi    0xc41ffd9c0d
ERR: rsi    0x30
ERR: rbp    0xc420093580
ERR: rsp    0xc4200934f0
ERR: r8     0x0
ERR: r9     0x0
ERR: r10    0xed495b
ERR: r11    0x6
ERR: r12    0x0
ERR: r13    0xf3
ERR: r14    0x33
ERR: r15    0xaa
ERR: rip    0x40fbeb
ERR: rflags 0x246
ERR: cs     0x33
ERR: fs     0x0
ERR: gs     0x0
==============================Global After Each==============================

• Failure [4.327 seconds]
running plugins signal handling will wait for the plugin to terminate [It] when SIGQUIT 
/tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

  No future change is possible.  Bailing out early after 0.041s.
  Got stuck at:
      
  Waiting for:
      Slept for 3000 ms

  /tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/integration/plugin/runner_test.go:88
------------------------------
•••
------------------------------

CMD> cf api https://api.tartine.cli.fun --skip-ssl-validation 
OUT: Setting api endpoint to https://api.tartine.cli.fun...
OUT: OK
OUT: 
OUT: api endpoint:   https://api.tartine.cli.fun
OUT: api version:    2.107.0
OUT: Not logged in. Use 'cf login' to log in.

CMD> cf auth admin u4a5sqn0km8nblhmsek5 
OUT: API endpoint: https://api.tartine.cli.fun
OUT: Authenticating...
OUT: OK
OUT: Use 'cf target' to view or set your target org and space.

CMD> cf remove-plugin-repo CF-Community 
OUT: 
OUT: OK
OUT: CF-Community removed from list of repositories
OUT: 

CMD> cf install-plugin -f /tmp/gexec_artifacts834221273/g280213092/test_plugin 
OUT: Attention: Plugins are binaries written by potentially untrusted authors.
OUT: Install and use plugins at your own risk.
OUT: Installing plugin CF-CLI-Integration-Test-Plugin...
OUT: OK
OUT: Plugin CF-CLI-Integration-Test-Plugin 1.2.4 successfully installed.

CMD> cf Sleep 3000 
ERR: SIGQUIT: quit
ERR: PC=0x40fa1e m=0 sigcode=0
ERR: 
ERR: goroutine 1 [running, locked to thread]:
ERR: runtime.mallocgc(0x10, 0xc91f60, 0xc42048f301, 0xc4203eff58)
ERR: 	/usr/local/go/src/runtime/malloc.go:632 +0x18e fp=0xc42017fb50 sp=0xc42017fab0 pc=0x40fa1e
ERR: runtime.convT2Estring(0xc91f60, 0xc42017fcb0, 0x0, 0x0)
ERR: 	/usr/local/go/src/runtime/iface.go:365 +0x6a fp=0xc42017fb80 sp=0xc42017fb50 pc=0x40db4a
ERR: code.cloudfoundry.org/cli/cf/commands/quota.(*UpdateQuota).MetaData(0xc420492ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
ERR: 	/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/commands/quota/update_quota.go:53 +0xe16 fp=0xc42017fde0 sp=0xc42017fb80 pc=0xa0dc76
ERR: code.cloudfoundry.org/cli/cf/commandregistry.Register(0xee93c0, 0xc420492ea0)
ERR: 	/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/commandregistry/registry.go:58 +0x4c fp=0xc42017ff08 sp=0xc42017fde0 pc=0x90c34c
ERR: code.cloudfoundry.org/cli/cf/commands/quota.init.4()
ERR: 	/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/commands/quota/update_quota.go:27 +0x3d fp=0xc42017ff28 sp=0xc42017ff08 pc=0xa0ce4d
ERR: code.cloudfoundry.org/cli/cf/commands/quota.init()
ERR: 	<autogenerated>:1 +0xa7 fp=0xc42017ff38 sp=0xc42017ff28 pc=0xa0f8a7
ERR: code.cloudfoundry.org/cli/cf/commandsloader.init()
ERR: 	<autogenerated>:1 +0x75 fp=0xc42017ff48 sp=0xc42017ff38 pc=0xa5e6c5
ERR: code.cloudfoundry.org/cli/cf/cmd.init()
ERR: 	<autogenerated>:1 +0x66 fp=0xc42017ff58 sp=0xc42017ff48 pc=0xa68146
ERR: main.init()
ERR: 	<autogenerated>:1 +0x5f fp=0xc42017ff88 sp=0xc42017ff58 pc=0xbfa30f
ERR: runtime.main()
ERR: 	/usr/local/go/src/runtime/proc.go:186 +0x1ca fp=0xc42017ffe0 sp=0xc42017ff88 pc=0x42ac8a
ERR: runtime.goexit()
ERR: 	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42017ffe8 sp=0xc42017ffe0 pc=0x455be1
ERR: 
ERR: goroutine 5 [syscall]:
ERR: os/signal.signal_recv(0x0)
ERR: 	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
ERR: os/signal.loop()
ERR: 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
ERR: created by os/signal.init.0
ERR: 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
ERR: 
ERR: rax    0x7f60dc4ac458
ERR: rbx    0x0
ERR: rcx    0xc420000180
ERR: rdx    0x13e2460
ERR: rdi    0xc91f60
ERR: rsi    0x10
ERR: rbp    0xc42017fb40
ERR: rsp    0xc42017fab0
ERR: r8     0x0
ERR: r9     0x0
ERR: r10    0xc4203f6420
ERR: r11    0x0
ERR: r12    0xffffffffffffffff
ERR: r13    0x22
ERR: r14    0x21
ERR: r15    0x100
ERR: rip    0x40fa1e
ERR: rflags 0x246
ERR: cs     0x33
ERR: fs     0x0
ERR: gs     0x0
==============================Global After Each==============================

• Failure [4.793 seconds]
running plugins signal handling will wait for the plugin to terminate [It] when SIGQUIT 
/tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

  No future change is possible.  Bailing out early after 0.051s.
  Got stuck at:
      
  Waiting for:
      Slept for 3000 ms

  /tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/integration/plugin/runner_test.go:88
------------------------------
• [SLOW TEST:69.319 seconds]
plugin API GetService and GetServices GetService gets the given service instance and GetServices returns a list of services instances 
/tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/integration/plugin/api_test.go:169
------------------------------
••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

Summarizing 4 Failures:

[Fail] running plugins signal handling will wait for the plugin to terminate [It] when SIGINT 
/tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/integration/plugin/runner_test.go:88

[Fail] running plugins signal handling will wait for the plugin to terminate [It] when SIGINT 
/tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/integration/plugin/runner_test.go:88

[Fail] running plugins signal handling will wait for the plugin to terminate [It] when SIGQUIT 
/tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/integration/plugin/runner_test.go:88

[Fail] running plugins signal handling will wait for the plugin to terminate [It] when SIGQUIT 
/tmp/build/06eff510/go/src/code.cloudfoundry.org/cli/integration/plugin/runner_test.go:88

Ran 140 of 140 Specs in 179.577 seconds
```

**Comment by XenoPhex** [comment]
@46bit Despite the revert, we would like to make this enhancement possible, but our current plug-in architecture requires a review and possible overhaul. The segfault above is just one example of a small change having weird affects that not even this team is capable of understanding. Because of this, we're starting the process of reviewing the open/closed issues around it and getting user feedback as to what needs to change.

For now, we are going to keep this issue closed, but feel free to provide input [here](https://www.pivotaltracker.com/story/show/157201049) where you can provide feedback.
