### ISSUE TITLE
`cf events` panics when the "request" field in event metadata is a string

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cli#1391]
Hello CLI Team, stumbled upon the following while working on [#154984642](https://www.pivotaltracker.com/story/show/154984642). We ended up changing the requirements in the story to accommodate the CLI, but in the future would like to be able to avoid having to put intermediary keys under `metadata.request` on the events.

## Command  

`cf events <my-app>`

## What occurred

```
 map: []interface {}
		Something unexpected happened. This is a bug in cf.

		Please re-run the command that caused this exception with the environment
		variable CF_TRACE set to true.

		Also, please update to the latest cli and try the command again:
		https://code.cloudfoundry.org/cli/releases

		Please create an issue at: https://code.cloudfoundry.org/cli/issues

		Include the below information when creating the issue:

		Command
		cf events dora -v

		CLI Version
		6.37.0+a40009753.2018-05-25

		Error
		NewMap called with unexpected argument

		Stack Trace
			goroutine 1 [running]:
	code.cloudfoundry.org/cli/util/panichandler.HandlePanic()
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/panichandler/handler.go:19 +0x8a
	panic(0x190a4c0, 0x1b62410)
		/usr/local/go/src/runtime/panic.go:491 +0x283
	code.cloudfoundry.org/cli/util/generic.NewMap(0xc420154750, 0x1, 0x1, 0x190a4c0, 0xc4202a72f0)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/generic/map.go:58 +0x788
	code.cloudfoundry.org/cli/cf/api/resources.EventResourceNewV2.ToFields(0xc4205c1e60, 0x24, 0xc4205c1e90, 0x2f, 0x0, 0xed2a3aa91, 0x0, 0xc42025cb60, 0x18, 0xc4205c1ef0, ...)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/api/resources/events.go:42 +0x2f0
	code.cloudfoundry.org/cli/cf/api/resources.(*EventResourceNewV2).ToFields(0xc4202c8380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
		<autogenerated>:1 +0x99
	code.cloudfoundry.org/cli/cf/api/appevents.CloudControllerAppEventsRepository.listEvents.func1(0x19ca3c0, 0xc4202c8380, 0xc42060a001)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/api/appevents/app_events.go:50 +0x76
	code.cloudfoundry.org/cli/cf/net.Gateway.ListPaginatedResources(0x22d5f88, 0xc4200b2e70, 0x1ac45b0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x22d5c88, 0xc42045c580, ...)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/net/gateway.go:155 +0xa4
	code.cloudfoundry.org/cli/cf/api/appevents.CloudControllerAppEventsRepository.listEvents(0x22d5c88, 0xc42045c580, 0x22d5f88, 0xc4200b2e70, 0x1ac45b0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, ...)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/api/appevents/app_events.go:44 +0x271
	code.cloudfoundry.org/cli/cf/api/appevents.CloudControllerAppEventsRepository.RecentEvents(0x22d5c88, 0xc42045c580, 0x22d5f88, 0xc4200b2e70, 0x1ac45b0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, ...)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/api/appevents/app_events.go:33 +0x125
	code.cloudfoundry.org/cli/cf/api/appevents.(*CloudControllerAppEventsRepository).RecentEvents(0xc4201b4500, 0xc420017560, 0x24, 0x32, 0xc420296c20, 0xc420013255, 0xb, 0x0, 0x0)
		<autogenerated>:1 +0x98
	code.cloudfoundry.org/cli/cf/commands/application.(*Events).Execute(0xc42019c9c0, 0x1faa880, 0xc42045c800, 0x1faa880, 0xc42045c800)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/commands/application/events.go:74 +0x7ed
	code.cloudfoundry.org/cli/cf/cmd.Main(0x0, 0x0, 0xc42000e100, 0x4, 0x4)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/cmd/cmd.go:121 +0xd22
	main.handleError(0x1f9a020, 0x209d760, 0x1fa0520, 0xc4201a5900, 0x1f9a020, 0x209d760)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/main.go:245 +0x4df
	main.executionWrapper(0x22d57a0, 0x208aea0, 0xc4201efc80, 0x0, 0x3, 0x0, 0x0)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/main.go:216 +0x28c
	code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc42035a180, 0xc42000e110, 0x3, 0x3, 0x2315320, 0x0, 0xc420000180, 0xc4201497a0, 0x2269000)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags/parser.go:314 +0x7fa
	main.parse(0xc42000e110, 0x3, 0x3, 0xc4202a6050)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/main.go:52 +0xad
	main.main()
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/main.go:43 +0x82

	goroutine 5 [syscall]:
	os/signal.signal_recv(0x0)
		/usr/local/go/src/runtime/sigqueue.go:131 +0xa7
	os/signal.loop()
		/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
	created by os/signal.init.0
		/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

	goroutine 602 [chan receive]:
	code.cloudfoundry.org/cli/util/configv3.catchSignal(0xc420262660, 0xc420620000, 0x27)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/configv3/write_config.go:56 +0x39
	created by code.cloudfoundry.org/cli/util/configv3.WriteConfig
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/configv3/write_config.go:40 +0x2f1

	goroutine 128 [select, locked to thread]:
	runtime.gopark(0x1ac5d58, 0x0, 0x1a80630, 0x6, 0x18, 0x1)
		/usr/local/go/src/runtime/proc.go:287 +0x12c
	runtime.selectgo(0xc42044e750, 0xc4205bed20)
		/usr/local/go/src/runtime/select.go:395 +0x1149
	runtime.ensureSigM.func1()
		/usr/local/go/src/runtime/signal_unix.go:511 +0x1fe
	runtime.goexit()
		/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1


		Your Platform Details
		e.g. Mac OS X 10.11, Windows 8.1 64-bit, Ubuntu 14.04.3 64-bit

		Shell
		e.g. Terminal, iTerm, Powershell, Cygwin, gnome-terminal, terminator
```

## What you expected to occur

Expected the command to succeed.

## CLI Version  

`cf version 6.37.0+a40009753.2018-05-25`

## CC API Endpoint Version  

This was on development code of the CC API. We were creating a new event that had a different than usual structure for its metadata:

```
"metadata": {
      "request": "---\napplications:\n- name: dora\n  instances: 2\n  buildpack: ruby_buildpack\n  env: PRIVATE DATA HIDDEN\n"
 },
```

Historically the value of `"request"` has usually been something that the CF CLI can convert into a Go map (because request bodies have been JSON objects), but we now have endpoints that take non-JSON (such as YAML) and we'd like to be able to put these (strings) as the value of `"request"`.

## CF Trace

The specific event that caused this error looked like this:

```

    "metadata": {
      "request": "---\napplications:\n- name: dora\n  instances: 2\n  buildpack: ruby_buildpack\n  env: PRIVATE DATA HIDDEN\n"
    },
    "space_guid": "f67acf6d-acf8-4158-8fb9-0233c2f5dc48",
    "organization_guid": "129069fa-2fbb-4640-a10d-2f10289d3d27"
  }
},
```
## Platform & Shell Details  

Platform: `Mac OS X 10.12.6 iTerm`

Thanks!

**Comment by abbyachau** [comment]
Hey @tcdowney thanks for creating this issue. Spoke with @zrob and since it sounds like there's a workaround at the moment, we've asked you folks to let us know if the workaround is no longer sufficient/this becomes more of a problem. Thanks.

**Comment by abbyachau** [comment]
Hi @tcdowney thanks again for creating this. Please could you let us know how to proceed with this issue? Thanks again.

**Comment by tcdowney** [comment]
We ended up putting an intermediary key in the event metadata so that the CLI could parse the event. See: https://github.com/cloudfoundry/cloud_controller_ng/commit/ba7b096012b38cc666c924e422b51eddbadf3424

The issue with the CLI requiring the value of `"request": {}` being an object instead of a string still exists, but as far as I know there aren't any events that Cloud Controller currently emits that would cause this.

If you want to close this, that's fine.
