### ISSUE TITLE
Command cf login

### ISSUE THREAD

**Issue by devshark** [cloudfoundry/cli#1519]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I am trying to login using cf

**What happened**
I was just trying to login for the first time after setting up and running [UAA Locally](https://docs.cloudfoundry.org/concepts/architecture/uaa.html#local). I've set both uaac and cf targets and they both work fine.
```bash
$ uaac target http://localhost:8080/uaa
Unknown key: Max-Age = 86400
Target: http://localhost:8080/uaa
$ CF_TRACE=1 cf target http://localhost:8080/api
Setting api endpoint to http://localhost:8080/api...
Warning: Insecure http API endpoint detected: secure https API endpoints are recommended
OK
api endpoint:   http://localhost:8080/api
api version:
Not logged in. Use 'cf login' to log in.
$ cf login
API endpoint: http://localhost:8080/api

                Something unexpected happened. This is a bug in cf.

                Please re-run the command that caused this exception with the environment
                variable CF_TRACE set to true.

                Also, please update to the latest cli and try the command again:
                https://code.cloudfoundry.org/cli/releases

                Please create an issue at: https://code.cloudfoundry.org/cli/issues

                Include the below information when creating the issue:

                Command
                cf login

                CLI Version
                6.41.0+dd4c76cdd.2018-11-28

                Error
                runtime error: index out of range

                Stack Trace
                        goroutine 1 [running]:
        code.cloudfoundry.org/cli/util/panichandler.HandlePanic()
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/panichandler/handler.go:19 +0x8d
        panic(0xd7d8c0, 0x17417e0)
                /usr/local/go/src/runtime/panic.go:513 +0x1b9
        code.cloudfoundry.org/cli/cf/net.getBaseDomain(0xc0001d9a80, 0x1f, 0x1f, 0x916b6d67ec1a01d6)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/net/http_client.go:106 +0xf8
        code.cloudfoundry.org/cli/cf/net.(*client).checkRedirect(0xc00000b3c0, 0xc00010fe00, 0xc0001764f8, 0x1, 0x1, 0x7, 0xc000508420)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/net/http_client.go:53 +0x7c
        code.cloudfoundry.org/cli/cf/net.(*client).checkRedirect-fm(0xc00010fe00, 0xc0001764f8, 0x1, 0x1, 0xc0001d7680, 0x21)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/net/http_client.go:38 +0x52
        net/http.(*Client).checkRedirect(0xc00008e150, 0xc00010fe00, 0xc0001764f8, 0x1, 0x1, 0x0, 0x1)
                /usr/local/go/src/net/http/client.go:416 +0x60
        net/http.(*Client).do(0xc00008e150, 0xc00010f600, 0x0, 0x0, 0x0)
                /usr/local/go/src/net/http/client.go:607 +0x8ba
        net/http.(*Client).Do(0xc00008e150, 0xc00010f600, 0x0, 0x0, 0x0)
                /usr/local/go/src/net/http/client.go:509 +0x35
        code.cloudfoundry.org/cli/cf/net.Gateway.doRequest(0x7f4087e7ad20, 0xc0000d4e70, 0xef0758, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f4087e7aa30, 0xc0001705c0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/net/gateway.go:423 +0xe9
        code.cloudfoundry.org/cli/cf/net.Gateway.doRequestAndHandlerError(0x7f4087e7ad20, 0xc0000d4e70, 0xef0758, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f4087e7aa30, 0xc0001705c0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/net/gateway.go:395 +0x7c
        code.cloudfoundry.org/cli/cf/net.Gateway.doRequestHandlingAuth(0x7f4087e7ad20, 0xc0000d4e70, 0xef0758, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f4087e7aa30, 0xc0001705c0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/net/gateway.go:366 +0x7e
        code.cloudfoundry.org/cli/cf/net.Gateway.performRequestForResponseBytes(0x7f4087e7ad20, 0xc0000d4e70, 0xef0758, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f4087e7aa30, 0xc0001705c0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/net/gateway.go:245 +0x9c
        code.cloudfoundry.org/cli/cf/net.Gateway.PerformRequestForJSONResponse(0x7f4087e7ad20, 0xc0000d4e70, 0xef0758, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f4087e7aa30, 0xc0001705c0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/net/gateway.go:265 +0xa6
        code.cloudfoundry.org/cli/cf/net.Gateway.GetResource(0x7f4087e7ad20, 0xc0000d4e70, 0xef0758, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f4087e7aa30, 0xc0001705c0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/net/gateway.go:93 +0x154
        code.cloudfoundry.org/cli/cf/api.RemoteInfoRepository.getCCAPIInfo(0x7f4087e7ad20, 0xc0000d4e70, 0xef0758, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f4087e7aa30, 0xc0001705c0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/api/endpoints.go:42 +0x111
        code.cloudfoundry.org/cli/cf/api.RemoteInfoRepository.GetCCInfo(0x7f4087e7ad20, 0xc0000d4e70, 0xef0758, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f4087e7aa30, 0xc0001705c0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/api/endpoints.go:23 +0x86
        code.cloudfoundry.org/cli/cf/configuration/coreconfig.APIConfigRefresher.Refresh(0x1021f20, 0xc00014e360, 0x7f4087e7ab40, 0xc0001705c0, 0xc0001d9140, 0x19, 0x6e, 0xb, 0xc0002f6360, 0xc0004947e0)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/configuration/coreconfig/api_config_refresher.go:22 +0x4f
        code.cloudfoundry.org/cli/cf/commands.API.setAPIEndpoint(0x103c4c0, 0xc000170580, 0x1021f20, 0xc00014e360, 0x7f4087e7ab40, 0xc0001705c0, 0xc0001d9140, 0x19, 0xc000034500, 0xea774c, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/commands/api.go:101 +0x196
        code.cloudfoundry.org/cli/cf/commands.(*Login).Execute(0xc000402000, 0x1040460, 0xc000171080, 0x0, 0x0)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/commands/login.go:94 +0x1bb
        code.cloudfoundry.org/cli/cf/cmd.Main(0x0, 0x0, 0xc00000a080, 0x2, 0x2)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/cmd/cmd.go:121 +0xccb
        main.handleError(0x1022f00, 0x177c920, 0x1029500, 0xc00053a180, 0x1022f00, 0x177c920)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/main.go:244 +0x518
        main.executionWrapper(0x7f4088076be8, 0x176a250, 0xc000157060, 0x0, 0x1, 0x0, 0x0)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/main.go:221 +0x285
        code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000531030, 0xc00000a090, 0x1, 0x1, 0xea5eeb, 0x1, 0x8, 0x10, 0xc000509150)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags/parser.go:331 +0x7c7
        main.parse(0xc00000a090, 0x1, 0x1, 0xd82b00, 0x1767980, 0xc00008c058)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/main.go:57 +0xaa
        main.main()
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/main.go:45 +0xa3

        goroutine 5 [syscall]:
        os/signal.signal_recv(0x0)
                /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
        os/signal.loop()
                /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
        created by os/signal.init.0
                /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

        goroutine 612 [chan receive]:
        code.cloudfoundry.org/cli/util/configv3.catchSignal(0xc000173e00, 0xc0004b0030, 0x26)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/configv3/write_config.go:56 +0x39
        created by code.cloudfoundry.org/cli/util/configv3.WriteConfig
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/configv3/write_config.go:40 +0x2dc
```

**Expected behavior**
I should be prompted for my login credentials, proceed with my setup. 

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `CF_TRACE=1 cf login`
2. See error above.

**Provide more context**
- Ubuntu 18.10 64-bit, Terminal
- cf version 6.41.0+dd4c76cdd.2018-11-28
- [4.24.0](https://docs.cloudfoundry.org/api/uaa/version/4.24.0/index.html)

Note: As of January 2018, we no longer support API versions older than 2.69.0/3.4.0 (CF Release: 251 / CAPI Release: 1.15.0)

**Comment by jenspinney** [comment]
@devshark Thanks for reporting this! 

We found the [problem code](https://github.com/cloudfoundry/cli/blob/master/cf/net/http_client.go#L106). In that code, we assume all hostnames have at least one `.` character, which doesn't work for `localhost`. The fix shouldn't be difficult, but we aren't sure whether you may encounter other problems using `localhost`. We'll prioritize this bug, but in the meantime, as a workaround, you could add an entry to your `/etc/hosts` file to make something like `localhost.com` point to `127.0.0.1`.

Thanks again for the bug report :)

**Comment by abbyachau** [comment]
Hi @devshark please let us know if you are still having issues and if you are could you please try @Ema93sh's suggestion. Thank you.

**Comment by devshark** [comment]
Hi, @Ema93sh is right. I was pointing cf-cli to UAA instead of CC. In fact, I don't need CC at all for now. I'm closing this issue.
