### ISSUE TITLE
cf7 push -t 300 fails with maximum exceeded

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/cli#1885]
**Describe the bug and the command you saw an issue with**
In our CF foundation we have configured cc.maximum_health_check_timeout = 600.
If I try to push an app with cf7 and a health check timeout of 300s, it fails with error message "health_check_timeout Maximum exceeded: max 180s".

cf push with cf cli v6 works as expected.

**Expected behavior**
"cf7 push -t 300" shall succeed on a foundation that is configured with  cc.maximum_health_check_timeout = 600.

**To Reproduce**
Given a directory with an index.html file:

Deployment with cf cli v6 succeeds:
```
stephan@WDFN34095835A:~/testapp$ cf push testapp -m 128M -b binary_buildpack -c "python3 -m http.server 8080" --random-route -t 300
Pushing app testapp to org uptime / space test as D047883...
Getting app info...
Creating app with these attributes...
+ name:                   testapp
  path:                   /home/stephan/testapp
  buildpacks:
+   binary_buildpack
+ command:                python3 -m http.server 8080
+ health check timeout:   300
+ memory:                 128M
  routes:
+   testapp-brash-duiker-tp.cfapps.sap.hana.ondemand.com
...
start command:   python3 -m http.server 8080
     state     since                  cpu    memory      disk      details
#0   running   2020-01-24T14:47:27Z   0.0%   0 of 128M   0 of 1G
```

Same command with cf7 fails:
```
tephan@WDFN34095835A:~/testapp$ cf7 --version
cf7 version 7.0.0-beta.28+84a90ee83.2020-01-03
stephan@WDFN34095835A:~/testapp$ cf7 push testapp -m 128M -b binary_buildpack -c "python3 -m http.server 8080" --random-route
 -t 300
Pushing app testapp to org uptime / space test as D047883...
For application 'testapp': health_check_timeout Maximum exceeded: max 180s
FAILED
```

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
Win10, WSL

- version of the CLI you are running
stephan@WDFN34095835A:~/testapp$ cf7 --version
cf7 version 7.0.0-beta.28+84a90ee83.2020-01-03

- version of the CC API Release you are on
CC API version: 3.79.0
cf-deployment 12.23

**Comment by stephanme** [comment]
I traced the "cf7 push -t 300" call and see that error message comes actually from the cloud controller:

```
REQUEST: [2020-02-05T15:36:32+01:00]
GET /v3/jobs/c39f9e82-e669-4442-8953-58d65e0a8542 HTTP/1.1
Host: api.cf.sap.hana.ondemand.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf7/7.0.0-beta.28+84a90ee83.2020-01-03 (go1.13.4; amd64 linux)

RESPONSE: [2020-02-05T15:36:32+01:00]
HTTP/1.1 200 OK
Content-Length: 658
Content-Type: application/json; charset=utf-8
Date: Wed, 05 Feb 2020 14:36:32 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload;
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Ratelimit-Limit: 40000
X-Ratelimit-Remaining: 39940
X-Ratelimit-Reset: 1580916893
X-Runtime: 0.018709
X-Vcap-Request-Id: 10e9ebb3-6fa1-4ffe-5c9a-ed01ec6f29d6::4ad8c1e0-00d5-4628-b26c-7c272395cb94
X-Xss-Protection: 1; mode=block
{
  "created_at": "2020-02-05T14:36:29Z",
  "errors": [
    {
      "code": 10008,
      "detail": "For application 'testapp': health_check_timeout Maximum exceeded: max 180s",
      "title": "CF-UnprocessableEntity"
    }
  ],
  "guid": "c39f9e82-e669-4442-8953-58d65e0a8542",
  "links": {
    "self": {
      "href": "https://api.cf.sap.hana.ondemand.com/v3/jobs/c39f9e82-e669-4442-8953-58d65e0a8542"
    },
    "space": {
      "href": "https://api.cf.sap.hana.ondemand.com/v3/spaces/b7c9dfa6-4d92-4851-a3a8-fad6204e51f0"
    }
  },
  "operation": "space.apply_manifest",
  "state": "FAILED",
  "updated_at": "2020-02-05T14:36:29Z",
  "warnings": null
}
```

In the cloud controller (cc-worker) I see the following stracktrace:

```
 {"timestamp":1580913389.4930775,"message":"Request failed: 422: {\"description\"=>\"For application 'testapp': health_check_timeout Maximum exceeded: max 180s\", \"error_code\"=>\"CF-UnprocessableEntity\", \"code\"=>10008, \"test_mode_info\"=>{\"description\"=>\"For application 'testapp': health_check_timeout Maximum exceeded: max 180s\", \"error_code\"=>\"CF-UnprocessableEntity\", \"backtrace\"=>[
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/space_apply_manifest_action_job.rb:29:in `rescue in block in perform'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/space_apply_manifest_action_job.rb:16:in `block in perform'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/space_apply_manifest_action_job.rb:15:in `each'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/space_apply_manifest_action_job.rb:15:in `perform'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/wrapping_job.rb:11:in `perform'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/wrapping_job.rb:11:in `perform'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/timeout_job.rb:13:in `block in perform'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/2.5.0/timeout.rb:33:in `catch'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/2.5.0/timeout.rb:33:in `catch'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/2.5.0/timeout.rb:108:in `timeout'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/timeout_job.rb:12:in `perform'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/wrapping_job.rb:11:in `perform'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/logging_context_job.rb:17:in `block in perform'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/logging_context_job.rb:63:in `with_request_id_set'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/logging_context_job.rb:15:in `perform'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/2.5.0/timeout.rb:103:in `timeout'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in start'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in start'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:173:in `block (2 levels) in start'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `loop'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `block in start'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:171:in `start'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/lib/tasks/jobs.rake:73:in `start_working'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/lib/tasks/jobs.rake:45:in `block (2 levels) in <top (required)>'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/task.rb:278:in `block in execute'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/task.rb:278:in `each'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/task.rb:278:in `execute'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/task.rb:218:in `block in invoke_with_call_chain'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/task.rb:198:in `invoke_with_call_chain'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/task.rb:187:in `invoke'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/application.rb:160:in `invoke_task'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/application.rb:116:in `each'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/application.rb:116:in `block in top_level'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/application.rb:125:in `run_with_threads'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/application.rb:110:in `top_level'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/application.rb:83:in `block in run'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/application.rb:186:in `standard_exception_handling'\",
\"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/gem_home/ruby/2.5.0/gems/rake-13.0.0/lib/rake/application.rb:80:in `run'\",
\"/var/vcap/packages/cloud_controller_ng/gem_home/ruby/2.5.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'\",
\"/var/vcap/packages/cloud_controller_ng/gem_home/ruby/2.5.0/bin/rake:23:in `load'\",
\"/var/vcap/packages/cloud_controller_ng/gem_home/ruby/2.5.0/bin/rake:23:in `<top (required)>'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:424:in `exec'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'\",
\"/var/vcap/packages/ruby-2.5.5-r0.10.0/bin/bundle:30:in `block in <main>'\",
\"/var/vcap/data/packages/ruby-2.5.5-r0.10.0/756aac13ce5856b9f069f2df1a956d5927af6ffd/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'\",
\"/var/vcap/packages/ruby-2.5.5-r0.10.0/bin/bundle:22:in `<main>'\"]}}","log_level":"info","source":"cc.background","data":{"request_guid":"646966de-e77c-4065-6717-8c7b564e4975::ecef70ae-61e5-437b-a294-23898c70d022","job_guid":"cc027387-5800-4ab5-8064-9862b75adadf"},"thread_id":47114796910080,"fiber_id":47114829869000,"process_id":6,"file":"/var/vcap/data/packages/cloud_controller_ng/0ff13852c91f676ea69dd321a501c5ef340bcfe6/cloud_controller_ng/app/jobs/logging_context_job.rb","lineno":41,"method":"block in log_error"}
```

**Comment by stephanme** [comment]
https://cloudfoundry.slack.com/archives/C07C04W4Q/p1580915713034200

RC was a missing cc.maximum_health_check_timeout configuration on cc-worker. One of our ops-files was buggy and configured only the api VMs.

**Comment by acrmp** [comment]
Thank you for taking the time to update the issue when you determined the cause.
