### ISSUE TITLE
Error 		runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhakina90** [cloudfoundry/cli#1912]
Something unexpected happened. This is a bug in cf.

		Please re-run the command that caused this exception with the environment
		variable CF_TRACE set to true.

		Include the below information when creating the issue:

		Command
		cf login -a ***  -o ***
 -s *** -u *** -p ***

		CLI Version
		6.50.0+4f0c3a2ce.2020-03-03

		Error
		runtime error: invalid memory address or nil pointer dereference

		Stack Trace
			goroutine 1 [running]:
	code.cloudfoundry.org/cli/util/panichandler.HandlePanic()
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/panichandler/handler.go:19 +0x81
	panic(0xfa54e0, 0x1b64d90)

**Comment by JenGoldstrich** [comment]
Hello @zhakina90 
```
$ cf login -a {} -u {} -p {} -o {} -s {}
API endpoint: {}

Authenticating...
OK

Targeted org jennatest

Targeted space space



API endpoint:   {} (API version: 2.146.0)
User:           admin
Org:            jennatest
Space:          space
```

I was not able to reproduce this issue on v6.50, is there more in your stack trace when you try to log in?

**Comment by mbnoimi** [comment]
I can reproduce the same bug as shown below:

**PS.** I use Linux Mint 20

```
$ cf login

API endpoint: https://0aa2db4c-6b30-4808-9a92-97af8b515b02-bluemix.cloudantnosqldb.appdomain.cloud/


                Something unexpected happened. This is a bug in cf.

                Please re-run the command that caused this exception with the environment
                variable CF_TRACE set to true.

                Also, please update to the latest cli and try the command again:
                https://code.cloudfoundry.org/cli/releases

                Please create an issue at: https://code.cloudfoundry.org/cli/issues

                Include the below information when creating the issue:

                Command
                cf login

                CLI Version
                6.53.0+8e2b70a4a.2020-10-01

                Error
                runtime error: invalid memory address or nil pointer dereference

                Stack Trace
                        goroutine 1 [running]:
        code.cloudfoundry.org/cli/util/panichandler.HandlePanic()
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/panichandler/handler.go:19 +0x81
        panic(0xfb7560, 0x1b82f30)
                /usr/local/go/src/runtime/panic.go:679 +0x1b2
        code.cloudfoundry.org/cli/api/cloudcontroller/ccv3.(*RealRequester).newHTTPRequest(0xc000448580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/api/cloudcontroller/ccv3/request.go:44 +0x56e
        code.cloudfoundry.org/cli/api/cloudcontroller/ccv3.(*RealRequester).buildRequest(0xc000448580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/api/cloudcontroller/ccv3/requester.go:216 +0x11b
        code.cloudfoundry.org/cli/api/cloudcontroller/ccv3.(*RealRequester).MakeRequest(0xc000448580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/api/cloudcontroller/ccv3/requester.go:95 +0x60
        code.cloudfoundry.org/cli/api/cloudcontroller/ccv3.(*Client).GetInfo(0xc00013e500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/api/cloudcontroller/ccv3/info.go:122 +0x1c7
        code.cloudfoundry.org/cli/api/cloudcontroller/ccv3.(*Client).TargetCF(0xc00013e500, 0x0, 0x0, 0xc0002f71a0, 0x54, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/api/cloudcontroller/ccv3/target.go:33 +0xd4
        code.cloudfoundry.org/cli/actor/v3action.Actor.SetTarget(0x13630e0, 0xc00013e500, 0x7eff983f50d8, 0xc0005f8300, 0x0, 0x0, 0x1330c20, 0x0, 0x0, 0xc000330800, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/actor/v3action/target.go:19 +0xd6
        code.cloudfoundry.org/cli/command/v6.(*LoginCommand).targetAPI(0x1bb0c08, 0x0, 0x758900, 0xc0002f71a0, 0x54, 0x0, 0x0)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/command/v6/login_command.go:293 +0x6e
        code.cloudfoundry.org/cli/command/v6.(*LoginCommand).Execute(0x1bb0c08, 0xc000402240, 0x0, 0x1, 0x0, 0x0)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/command/v6/login_command.go:134 +0x133
        code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).executionWrapper(0xc0005e2420, 0x7eff983f5058, 0x1bb0c08, 0xc000402240, 0x0, 0x1, 0x0, 0x0)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/command_parser/command_parser.go:93 +0x252
        code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000462070, 0xc00000c0b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags/parser.go:331 +0x89c
        code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).parse(0xc0005e2420, 0xc00000c0b0, 0x1, 0x1, 0xfbcec0, 0x1bae240, 0xc0004dbe20, 0x3d, 0xc0004dbe70)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/command_parser/command_parser.go:221 +0xe0
        code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).ParseCommandFromArgs(...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/command_parser/command_parser.go:57
        main.main()
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/main.go:40 +0x19e

        goroutine 6 [syscall]:
        os/signal.signal_recv(0x0)
                /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
        os/signal.loop()
                /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
        created by os/signal.init.0
                /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

        goroutine 607 [IO wait]:
        internal/poll.runtime_pollWait(0x7eff98433d68, 0x72, 0xffffffffffffffff)
                /usr/local/go/src/runtime/netpoll.go:184 +0x55
        internal/poll.(*pollDesc).wait(0xc00045c298, 0x72, 0x1000, 0x10a6, 0xffffffffffffffff)
                /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
        internal/poll.(*pollDesc).waitRead(...)
                /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
        internal/poll.(*FD).Read(0xc00045c280, 0xc000112600, 0x10a6, 0x10a6, 0x0, 0x0, 0x0)
                /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
        net.(*netFD).Read(0xc00045c280, 0xc000112600, 0x10a6, 0x10a6, 0x203000, 0x400, 0x7eff984c8500)
                /usr/local/go/src/net/fd_unix.go:202 +0x4f
        net.(*conn).Read(0xc00017e038, 0xc000112600, 0x10a6, 0x10a6, 0x0, 0x0, 0x0)
                /usr/local/go/src/net/net.go:184 +0x68
        crypto/tls.(*atLeastReader).Read(0xc0007180a0, 0xc000112600, 0x10a6, 0x10a6, 0xc00070e8c0, 0x41718e, 0xc00070e8a0)
                /usr/local/go/src/crypto/tls/conn.go:780 +0x60
        bytes.(*Buffer).ReadFrom(0xc000067058, 0x131ba80, 0xc0007180a0, 0x409d05, 0xfd70a0, 0x1103140)
                /usr/local/go/src/bytes/buffer.go:204 +0xb4
        crypto/tls.(*Conn).readFromUntil(0xc000066e00, 0x131be40, 0xc00017e038, 0x5, 0xc00017e038, 0x1066900)
                /usr/local/go/src/crypto/tls/conn.go:802 +0xec
        crypto/tls.(*Conn).readRecordOrCCS(0xc000066e00, 0x0, 0x0, 0x3)
                /usr/local/go/src/crypto/tls/conn.go:609 +0x124
        crypto/tls.(*Conn).readRecord(...)
                /usr/local/go/src/crypto/tls/conn.go:577
        crypto/tls.(*Conn).Read(0xc000066e00, 0xc00011d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
                /usr/local/go/src/crypto/tls/conn.go:1255 +0x161
        net/http.(*persistConn).Read(0xc000404000, 0xc00011d000, 0x1000, 0x1000, 0xc000712000, 0xc00070ec20, 0x404d15)
                /usr/local/go/src/net/http/transport.go:1758 +0x75
        bufio.(*Reader).fill(0xc000187980)
                /usr/local/go/src/bufio/bufio.go:100 +0x103
        bufio.(*Reader).Peek(0xc000187980, 0x1, 0x0, 0x0, 0x1, 0xc00020ac00, 0x0)
                /usr/local/go/src/bufio/bufio.go:138 +0x4f
        net/http.(*persistConn).readLoop(0xc000404000)
                /usr/local/go/src/net/http/transport.go:1911 +0x1d6
        created by net/http.(*Transport).dialConn
                /usr/local/go/src/net/http/transport.go:1580 +0xb0d

        goroutine 608 [select]:
        net/http.(*persistConn).writeLoop(0xc000404000)
                /usr/local/go/src/net/http/transport.go:2210 +0x123
        created by net/http.(*Transport).dialConn
                /usr/local/go/src/net/http/transport.go:1581 +0xb32

        goroutine 641 [chan receive]:
        code.cloudfoundry.org/cli/util/configv3.catchSignal(0xc000776060, 0xc000640210, 0x26)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/configv3/write_config.go:55 +0x34
        created by code.cloudfoundry.org/cli/util/configv3.(*Config).WriteConfig
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/configv3/write_config.go:40 +0x2c9


                Your Platform Details
                e.g. Mac OS X 10.11, Windows 8.1 64-bit, Ubuntu 14.04.3 64-bit

                Shell
                e.g. Terminal, iTerm, Powershell, Cygwin, gnome-terminal, terminator
```

**Comment by xinyi1989** [comment]
The same error, Please help to solve it

**Comment by adib** [comment]
Same error in macOS 12.0.1, Intel, CLI version 6.53.0+8e2b70a4a.2020-10-01

```
		Command
		cf push

		CLI Version
		6.53.0+8e2b70a4a.2020-10-01

		Error
		runtime error: invalid memory address or nil pointer dereference

		Stack Trace
			goroutine 1 [running]:
	code.cloudfoundry.org/cli/util/panichandler.HandlePanic()
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/util/panichandler/handler.go:19 +0x81
	panic(0x1bbc620, 0x27ad4b0)
		/usr/local/Cellar/go/1.13.8/libexec/src/runtime/panic.go:679 +0x1b2
	code.cloudfoundry.org/cli/cf/api/resources.NewApplicationEntityFromAppParams(0x0, 0x0, 0x0, 0x0, 0xc000436980, 0xc0004e1110, 0x0, 0x0, 0x0, 0xc000014000, ...)
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/cf/api/resources/applications.go:128 +0x1f1
	code.cloudfoundry.org/cli/cf/api/applications.CloudControllerRepository.Update(0x2e3d288, 0xc0001a6cc0, 0x2e3d590, 0xc000022bb0, 0x1d9ade0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, ...)
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/cf/api/applications/applications.go:96 +0x85
	code.cloudfoundry.org/cli/cf/commands/application.(*Push).Execute(0xc000160a20, 0x1f5c0a0, 0xc0001a7c80, 0x1f5c0a0, 0xc0001a7c80)
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/cf/commands/application/push.go:231 +0x714
	code.cloudfoundry.org/cli/cf/cmd.Main(0xc000040019, 0x4, 0xc00000e080, 0x2, 0x2)
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/cf/cmd/cmd.go:122 +0xca0
	code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).handleError(0xc00019aaf0, 0x1f231a0, 0xc0001a6ac0, 0x1, 0x1f231a0)
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/util/command_parser/command_parser.go:116 +0x4e1
	code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).executionWrapper(0xc00019aaf0, 0x2e36820, 0x27db0f8, 0xc000369220, 0x0, 0x1, 0x0, 0x0)
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/util/command_parser/command_parser.go:94 +0x277
	code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0004342a0, 0xc00000e090, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags/parser.go:331 +0x89c
	code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).parse(0xc00019aaf0, 0xc00000e090, 0x1, 0x1, 0x1bc1ec0, 0x27d8160, 0xc00054de9f, 0x3, 0xc00054de70)
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/util/command_parser/command_parser.go:221 +0xe0
	code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).ParseCommandFromArgs(...)
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/util/command_parser/command_parser.go:57
	main.main()
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/main.go:40 +0x19e
	
	goroutine 6 [syscall]:
	os/signal.signal_recv(0x0)
		/usr/local/Cellar/go/1.13.8/libexec/src/runtime/sigqueue.go:144 +0x96
	os/signal.loop()
		/usr/local/Cellar/go/1.13.8/libexec/src/os/signal/signal_unix.go:23 +0x22
	created by os/signal.init.0
		/usr/local/Cellar/go/1.13.8/libexec/src/os/signal/signal_unix.go:29 +0x41
	
	goroutine 121 [select]:
	net/http.(*persistConn).writeLoop(0xc0001610e0)
		/usr/local/Cellar/go/1.13.8/libexec/src/net/http/transport.go:2210 +0x123
	created by net/http.(*Transport).dialConn
		/usr/local/Cellar/go/1.13.8/libexec/src/net/http/transport.go:1581 +0xb32
	
	goroutine 640 [IO wait]:
	internal/poll.runtime_pollWait(0x2e35f08, 0x72, 0xffffffffffffffff)
		/usr/local/Cellar/go/1.13.8/libexec/src/runtime/netpoll.go:184 +0x55
	internal/poll.(*pollDesc).wait(0xc000302818, 0x72, 0x1b00, 0x1b4f, 0xffffffffffffffff)
		/usr/local/Cellar/go/1.13.8/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
	internal/poll.(*pollDesc).waitRead(...)
		/usr/local/Cellar/go/1.13.8/libexec/src/internal/poll/fd_poll_runtime.go:92
	internal/poll.(*FD).Read(0xc000302800, 0xc0003cc000, 0x1b4f, 0x1b4f, 0x0, 0x0, 0x0)
		/usr/local/Cellar/go/1.13.8/libexec/src/internal/poll/fd_unix.go:169 +0x22b
	net.(*netFD).Read(0xc000302800, 0xc0003cc000, 0x1b4f, 0x1b4f, 0x203000, 0x2c38100, 0x20300000000000)
		/usr/local/Cellar/go/1.13.8/libexec/src/net/fd_unix.go:202 +0x4f
	net.(*conn).Read(0xc00019e020, 0xc0003cc000, 0x1b4f, 0x1b4f, 0x0, 0x0, 0x0)
		/usr/local/Cellar/go/1.13.8/libexec/src/net/net.go:184 +0x68
	crypto/tls.(*atLeastReader).Read(0xc0006f40a0, 0xc0003cc000, 0x1b4f, 0x1b4f, 0xc00007f8c0, 0x1018fee, 0xc00007f8a0)
		/usr/local/Cellar/go/1.13.8/libexec/src/crypto/tls/conn.go:780 +0x60
	bytes.(*Buffer).ReadFrom(0xc000140258, 0x1f218e0, 0xc0006f40a0, 0x100ba85, 0x1bdc020, 0x1d08760)
		/usr/local/Cellar/go/1.13.8/libexec/src/bytes/buffer.go:204 +0xb4
	crypto/tls.(*Conn).readFromUntil(0xc000140000, 0x2e7a840, 0xc00019e020, 0x5, 0xc00019e020, 0x20)
		/usr/local/Cellar/go/1.13.8/libexec/src/crypto/tls/conn.go:802 +0xec
	crypto/tls.(*Conn).readRecordOrCCS(0xc000140000, 0x0, 0x0, 0x3)
		/usr/local/Cellar/go/1.13.8/libexec/src/crypto/tls/conn.go:609 +0x124
	crypto/tls.(*Conn).readRecord(...)
		/usr/local/Cellar/go/1.13.8/libexec/src/crypto/tls/conn.go:577
	crypto/tls.(*Conn).Read(0xc000140000, 0xc000133000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/local/Cellar/go/1.13.8/libexec/src/crypto/tls/conn.go:1255 +0x161
	net/http.(*persistConn).Read(0xc000160480, 0xc000133000, 0x1000, 0x1000, 0xc0006dc000, 0xc00007fc20, 0x1006a85)
		/usr/local/Cellar/go/1.13.8/libexec/src/net/http/transport.go:1758 +0x75
	bufio.(*Reader).fill(0xc0005d05a0)
		/usr/local/Cellar/go/1.13.8/libexec/src/bufio/bufio.go:100 +0x103
	bufio.(*Reader).Peek(0xc0005d05a0, 0x1, 0x0, 0x0, 0x1, 0xc000237700, 0x0)
		/usr/local/Cellar/go/1.13.8/libexec/src/bufio/bufio.go:138 +0x4f
	net/http.(*persistConn).readLoop(0xc000160480)
		/usr/local/Cellar/go/1.13.8/libexec/src/net/http/transport.go:1911 +0x1d6
	created by net/http.(*Transport).dialConn
		/usr/local/Cellar/go/1.13.8/libexec/src/net/http/transport.go:1580 +0xb0d
	
	goroutine 641 [select]:
	net/http.(*persistConn).writeLoop(0xc000160480)
		/usr/local/Cellar/go/1.13.8/libexec/src/net/http/transport.go:2210 +0x123
	created by net/http.(*Transport).dialConn
		/usr/local/Cellar/go/1.13.8/libexec/src/net/http/transport.go:1581 +0xb32
	
	goroutine 120 [IO wait]:
	internal/poll.runtime_pollWait(0x2e35e38, 0x72, 0xffffffffffffffff)
		/usr/local/Cellar/go/1.13.8/libexec/src/runtime/netpoll.go:184 +0x55
	internal/poll.(*pollDesc).wait(0xc0005b4398, 0x72, 0x1b00, 0x1b4f, 0xffffffffffffffff)
		/usr/local/Cellar/go/1.13.8/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
	internal/poll.(*pollDesc).waitRead(...)
		/usr/local/Cellar/go/1.13.8/libexec/src/internal/poll/fd_poll_runtime.go:92
	internal/poll.(*FD).Read(0xc0005b4380, 0xc0004f2000, 0x1b4f, 0x1b4f, 0x0, 0x0, 0x0)
		/usr/local/Cellar/go/1.13.8/libexec/src/internal/poll/fd_unix.go:169 +0x22b
	net.(*netFD).Read(0xc0005b4380, 0xc0004f2000, 0x1b4f, 0x1b4f, 0x203000, 0x580020000000000, 0x0)
		/usr/local/Cellar/go/1.13.8/libexec/src/net/fd_unix.go:202 +0x4f
	net.(*conn).Read(0xc000010028, 0xc0004f2000, 0x1b4f, 0x1b4f, 0x0, 0x0, 0x0)
		/usr/local/Cellar/go/1.13.8/libexec/src/net/net.go:184 +0x68
	crypto/tls.(*atLeastReader).Read(0xc0005d3340, 0xc0004f2000, 0x1b4f, 0x1b4f, 0x28, 0x8, 0xc00007c8a0)
		/usr/local/Cellar/go/1.13.8/libexec/src/crypto/tls/conn.go:780 +0x60
	bytes.(*Buffer).ReadFrom(0xc000177058, 0x1f218e0, 0xc0005d3340, 0x100ba85, 0x1bdc020, 0x1d08760)
		/usr/local/Cellar/go/1.13.8/libexec/src/bytes/buffer.go:204 +0xb4
	crypto/tls.(*Conn).readFromUntil(0xc000176e00, 0x2e7a840, 0xc000010028, 0x5, 0xc000010028, 0x20)
		/usr/local/Cellar/go/1.13.8/libexec/src/crypto/tls/conn.go:802 +0xec
	crypto/tls.(*Conn).readRecordOrCCS(0xc000176e00, 0x0, 0x0, 0x3)
		/usr/local/Cellar/go/1.13.8/libexec/src/crypto/tls/conn.go:609 +0x124
	crypto/tls.(*Conn).readRecord(...)
		/usr/local/Cellar/go/1.13.8/libexec/src/crypto/tls/conn.go:577
	crypto/tls.(*Conn).Read(0xc000176e00, 0xc000562000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/local/Cellar/go/1.13.8/libexec/src/crypto/tls/conn.go:1255 +0x161
	net/http.(*persistConn).Read(0xc0001610e0, 0xc000562000, 0x1000, 0x1000, 0xc00070c2a0, 0xc00007cc20, 0x1006a85)
		/usr/local/Cellar/go/1.13.8/libexec/src/net/http/transport.go:1758 +0x75
	bufio.(*Reader).fill(0xc00050b260)
		/usr/local/Cellar/go/1.13.8/libexec/src/bufio/bufio.go:100 +0x103
	bufio.(*Reader).Peek(0xc00050b260, 0x1, 0x0, 0x0, 0x1, 0xc0006dd200, 0x0)
		/usr/local/Cellar/go/1.13.8/libexec/src/bufio/bufio.go:138 +0x4f
	net/http.(*persistConn).readLoop(0xc0001610e0)
		/usr/local/Cellar/go/1.13.8/libexec/src/net/http/transport.go:1911 +0x1d6
	created by net/http.(*Transport).dialConn
		/usr/local/Cellar/go/1.13.8/libexec/src/net/http/transport.go:1580 +0xb0d
	
	goroutine 906 [chan receive]:
	code.cloudfoundry.org/cli/util/configv3.catchSignal(0xc00050b680, 0xc000243ec0, 0x27)
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/util/configv3/write_config.go:55 +0x34
	created by code.cloudfoundry.org/cli/util/configv3.(*Config).WriteConfig
		/Users/pivotal/concourse/volumes/live/4612d07c-5801-45d7-6360-b9336c5cb6b6/volume/gopath/src/code.cloudfoundry.org/cli/util/configv3/write_config.go:40 +0x2c9
```

**Comment by VGalata** [comment]
I have the same error when logging in though it was working with the same `cf` version a couple of months ago.

```
Command
cf login -a https://api.cf.reu.bsh-lando.com --sso -o HCCS -s Validation-REU

CLI Version
6.53.0+8e2b70a4a.2020-10-01

Error
runtime error: invalid memory address or nil pointer dereference
```

OS: `Ubuntu 22.04.1 LTS`
Shell: `zsh`

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket.
