### ISSUE TITLE
An occasional Panic on one of our RHEL boxes

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cli#201]
We get an occasional panic on some of our linux boxes.

Googling turned up this Go Bug that may be related fixed in 1.3: https://code.google.com/p/go/issues/detail?id=7848

Thoughts?

```
Error dumping response
 write tcp 10.255.1.20:80: broken pipe
 
 
 Aww shucks.
 
 Something completely unexpected happened. This is a bug in cf.
 Please file this bug : https://github.com/cloudfoundry/cli/issues
 Tell us that you ran this command:
 
 	cf push -f manifest-stage.yml
 
 this error occurred:
 
 	runtime error: invalid memory address or nil pointer dereference
 
 and this stack trace:
 
 	goroutine 1 [running]:
 	main.displayCrashDialog(0xc210a89c30, 0x40)
 		/home/ubuntu/go/src/github.com/cloudfoundry/cli/main/main.go:173 +0xe5
 	main.handlePanics()
 		/home/ubuntu/go/src/github.com/cloudfoundry/cli/main/main.go:136 +0x144
 	runtime.panic(0x87e660, 0xfe42c8)
 		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
 	io/ioutil.func·001()
 		/usr/local/go/src/pkg/io/ioutil/ioutil.go:29 +0xf0
 	runtime.panic(0x87e660, 0xfe42c8)
 		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
 	bytes.(*Buffer).ReadFrom(0xc210c381c0, 0x0, 0x0, 0x0, 0x0, ...)
 		/usr/local/go/src/pkg/bytes/buffer.go:169 +0x1f1
 	io/ioutil.readAll(0x0, 0x0, 0x200, 0x0, 0x0, ...)
 		/usr/local/go/src/pkg/io/ioutil/ioutil.go:32 +0x156
 	io/ioutil.ReadAll(0x0, 0x0, 0x0, 0x0, 0x0, ...)
 		/usr/local/go/src/pkg/io/ioutil/ioutil.go:41 +0x3f
 	github.com/cloudfoundry/cli/cf/net.Gateway.doRequestAndHandlerError(0x7f66284c4e88, 0xc2100aeb60, 0xa05cb8, 0x1, 0x12a05f200, ...)
 		/home/ubuntu/go/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net
```

**Comment by youngm** [comment]
I haven't seen this issue for a log time and 6.12.3 upgraded to go 1.4.2 so I'm going to close this for now.
