### ISSUE TITLE
[API/7] ERR Failed to stage build: staging failed

### ISSUE THREAD

**Issue by AxatMehta** [cloudfoundry/cli#2156]
C:\Users\lenovo\Desktop\IBM CLOUD\get-started-php>ibmcloud cf logs Test1-Nirma --recent
Invoking 'cf logs Test1-Nirma --recent'...

Retrieving logs for app Test1-Nirma in org akshatmehta40@gmail.com / space dev as akshatmehta40@gmail.com...

   2021-03-23T07:38:09.91+0530 [API/16] OUT Updated app with guid e8172ffc-8bac-40d0-8f3c-b5e81ad8a8ca ({"buildpack"=>"php_buildpack", "disk_quota"=>1024, "health_check_http_endpoint"=>"", "health_check_type"=>"port", "instances"=>1, "memory"=>64, "name"=>"Test1-Nirma", "space_guid"=>"abdd6ad3-adce-44f9-bfea-ecbe361e3bd4"})
   2021-03-23T07:38:11.41+0530 [API/11] OUT Uploading bits for app with guid e8172ffc-8bac-40d0-8f3c-b5e81ad8a8ca
   2021-03-23T07:38:18.79+0530 [API/14] OUT Updated app with guid e8172ffc-8bac-40d0-8f3c-b5e81ad8a8ca ({"state"=>"STOPPED"})
   2021-03-23T07:38:19.42+0530 [API/22] OUT Creating build for app with guid e8172ffc-8bac-40d0-8f3c-b5e81ad8a8ca
   2021-03-23T07:38:19.72+0530 [API/22] OUT Updated app with guid e8172ffc-8bac-40d0-8f3c-b5e81ad8a8ca ({"state"=>"STARTED"})
   2021-03-23T07:38:20.06+0530 [STG/0] OUT Downloading php_buildpack...
   2021-03-23T07:38:20.13+0530 [STG/0] OUT Downloaded php_buildpack
   2021-03-23T07:38:20.13+0530 [STG/0] OUT Cell 7f8c402c-73b7-4f13-be9d-cfb853fbd515 creating container for instance 5bd53e2a-03ae-434e-9b24-e5f83337ada2
   2021-03-23T07:38:20.98+0530 [STG/0] OUT Cell 7f8c402c-73b7-4f13-be9d-cfb853fbd515 successfully created container for instance 5bd53e2a-03ae-434e-9b24-e5f83337ada2
   2021-03-23T07:38:21.39+0530 [STG/0] OUT Downloading app package...
   2021-03-23T07:38:21.39+0530 [STG/0] OUT Downloading build artifacts cache...
   2021-03-23T07:38:21.56+0530 [STG/0] OUT Downloaded build artifacts cache (221B)
   2021-03-23T07:38:21.64+0530 [STG/0] OUT Downloaded app package (612.4K)
   2021-03-23T07:38:22.24+0530 [STG/0] OUT -------> Buildpack version 4.4.30
   2021-03-23T07:38:23.46+0530 [STG/0] ERR Traceback (most recent call last):
   2021-03-23T07:38:23.46+0530 [STG/0] ERR   File "/tmp/buildpacks/7d65ca84ef14c013d351e26313912510/scripts/compile.py", line 57, in <module>
   2021-03-23T07:38:23.46+0530 [STG/0] ERR     .from_build_pack('lib/additional_commands')
   2021-03-23T07:38:23.46+0530 [STG/0] ERR   File "/tmp/buildpacks/7d65ca84ef14c013d351e26313912510/lib/build_pack_utils/builder.py", line 246, in done
   2021-03-23T07:38:23.46+0530 [STG/0] ERR     process_extension(extn, self._builder._ctx, 'configure', process)
   2021-03-23T07:38:23.46+0530 [STG/0] ERR   File "/tmp/buildpacks/7d65ca84ef14c013d351e26313912510/lib/build_pack_utils/utils.py", line 69, in process_extension
   2021-03-23T07:38:23.46+0530 [STG/0] ERR     success(getattr(extn, to_call)(*args))
   2021-03-23T07:38:23.46+0530 [STG/0] ERR   File "/tmp/buildpacks/7d65ca84ef14c013d351e26313912510/extensions/composer/extension.py", line 424, in configure
   2021-03-23T07:38:23.46+0530 [STG/0] ERR     config.configure()
   2021-03-23T07:38:23.46+0530 [STG/0] ERR   File "/tmp/buildpacks/7d65ca84ef14c013d351e26313912510/extensions/composer/extension.py", line 152, in configure
   2021-03-23T07:38:23.46+0530 [STG/0] ERR     self._ctx['PHP_VERSION'] = self.pick_php_version(php_version)
   2021-03-23T07:38:23.46+0530 [STG/0] ERR   File "/tmp/buildpacks/7d65ca84ef14c013d351e26313912510/extensions/composer/extension.py", line 98, in pick_php_version
   2021-03-23T07:38:23.46+0530 [STG/0] ERR     return self._ctx['PHP_VERSION']
   2021-03-23T07:38:23.46+0530 [STG/0] ERR   File "/tmp/buildpacks/7d65ca84ef14c013d351e26313912510/lib/build_pack_utils/utils.py", line 151, in __getitem__
   2021-03-23T07:38:23.46+0530 [STG/0] ERR     return self.format(dict.__getitem__(self, key))
   2021-03-23T07:38:23.46+0530 [STG/0] ERR   File "/tmp/buildpacks/7d65ca84ef14c013d351e26313912510/lib/build_pack_utils/utils.py", line 142, in format
   2021-03-23T07:38:23.46+0530 [STG/0] ERR     val = val.format(**self)
   2021-03-23T07:38:23.46+0530 [STG/0] ERR KeyError: u'PHP_72_LATEST'
   2021-03-23T07:38:23.48+0530 [STG/0] ERR Failed to compile droplet: Failed to run finalize script: exit status 1
   2021-03-23T07:38:23.49+0530 [STG/0] OUT Exit status 223
   2021-03-23T07:38:23.62+0530 [STG/0] OUT Cell 7f8c402c-73b7-4f13-be9d-cfb853fbd515 stopping instance 5bd53e2a-03ae-434e-9b24-e5f83337ada2
   2021-03-23T07:38:23.62+0530 [STG/0] OUT Cell 7f8c402c-73b7-4f13-be9d-cfb853fbd515 destroying container for instance 5bd53e2a-03ae-434e-9b24-e5f83337ada2
   2021-03-23T07:38:23.88+0530 [API/7] ERR Failed to stage build: staging failed
   2021-03-23T07:38:24.69+0530 [STG/0] OUT Cell 7f8c402c-73b7-4f13-be9d-cfb853fbd515 successfully destroyed container for instance 5bd53e2a-03ae-434e-9b24-e5f83337ada2

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
