### ISSUE TITLE
cf -v panics when %HOMEDRIVE% does not exist

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cli#356]
This issue sounds similar to #355 but note the different error & stacktrace.

On my Windows 7 machine, HOMEDRIVE defaults to a remote drive mapped as I: at the office.
So at home it maps to a drive that does not exist. Note that I do NOT set CF_HOME here, I'm reporting a usability issue when forgetting to set that.

1. Not an unexpected error case, so should not show stacktrace
2. Why does cf -v need to access .cf\config.json anyway? It knows its version (6.10.0-b78bf10).
3. Suspicious message "panic: This shouldn't print anything"
4. Would be nice if cf recognized the situation and suggests me to set CF_HOME in the error message, or mention that it constructed the i:\.cf\config.json path from %HOMEDRIVE% (Windows 7 also has HOME, HOMEPATH and HOMESHARE preconfigured so it's not obvious which is the culprit) and we should review them.

```
c:\>cf -v
FAILED
Config error: open i:\.cf\config.json: The system cannot find the path specified.
panic: This shouldn't print anything

goroutine 1 [running]:
runtime.panic(0x8689c0, 0xc08404c6c0)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/src/pkg/runtime/panic.c:266 +0xc8
github.com/cloudfoundry/cli/cf/terminal.(*terminalUI).PanicQuietly(0xc084048cc0)
        C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/terminal/ui.go:164 +0x58
github.com/cloudfoundry/cli/cf/terminal.(*terminalUI).Failed(0xc084048cc0, 0xc08402ecc0, 0x51, 0x0, 0x0, ...)
        C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/terminal/ui.go:152 +0x26a
main.funcﾂｷ001(0x151738, 0xc084044db0)
        C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:55 +0x10e
github.com/cloudfoundry/cli/cf/configuration/core_config.funcﾂｷ001()
        C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/configuration/core_config/config_repository.go:107 +0x
85
sync.(*Once).Do(0xc08404c410, 0x2b6e90)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/src/pkg/sync/once.go:40 +0x9d
github.com/cloudfoundry/cli/cf/configuration/core_config.(*ConfigRepository).init(0xc0840446c0)
        C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/configuration/core_config/config_repository.go:109 +0x
5e
github.com/cloudfoundry/cli/cf/configuration/core_config.(*ConfigRepository).read(0xc0840446c0, 0x2b6ec8)
        C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/configuration/core_config/config_repository.go:115 +0x
5c
github.com/cloudfoundry/cli/cf/configuration/core_config.(*ConfigRepository).Locale(0xc0840446c0, 0x0, 0x0)
        C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/configuration/core_config/config_repository.go:294 +0x
7e
github.com/cloudfoundry/cli/cf/i18n.Init(0x151938, 0xc0840446c0, 0x151908, 0x12203e0, 0xc0840446c0)
        C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/i18n/init.go:46 +0x4a
main.setupDependencies(0x2bffa0)
        C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:62 +0x3d6
main.init()
        C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:31 +0xc0
```

**Comment by simonleung8** [comment]
Thanks for the suggestion.

We have improved the error message and will consider you suggestions.
