### ISSUE TITLE
Cannot use 'n' as a hostname without quoting it

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cli#402]
When a manifest includes an unquoted 'n' hostname, it is for some reason not considered a string and the CLI refuses to use it.

This manifest:

```yaml
hosts:
  - n

applications:
  - name: hosts-test
```

Produces this error when run with `cf push manifest.yml`:

```
	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf push -f manifest.yml

	using this version of the CLI:

		6.10.0-b78bf10

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x4)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:174 +0xa9
	main.handlePanics(0x10265d8, 0xc2100684e0)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:158 +0x123
	runtime.panic(0x543c80, 0xdf5119)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/manifest.mapToAppParams(0xc210177c40, 0x9, 0x1036440, 0xc21021b970, 0x0, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/manifest/manifest.go:140 +0x76b
	github.com/cloudfoundry/cli/cf/manifest.Manifest.Applications(0xc210177c40, 0x18, 0x1036440, 0xc21021b8e8, 0x0, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/manifest/manifest.go:43 +0x2ef
	github.com/cloudfoundry/cli/cf/commands/application.
```

Using the single "host" attribute, the error is a little nicer:

```yaml
host: n

applications:
  - name: hosts-test
```

```
FAILED
Error reading manifest file:
host must be a string value
```

In either case, if I quote the letter (e.g. `host: 'n'`) or change it to a different letter (e.g. `host: m`), the push succeeds.

**Comment by simonleung8** [comment]
The root cause of this lies in candiedyaml. You can see it is translating 'n' into false, which is not a `string` type.
https://github.com/cloudfoundry-incubator/candiedyaml/blob/master/resolver.go#L46

Because of this behavior, any string such as 'n', 'no', 'false' etc... will need to be in quotes. We will also update CLI to display a more friendly error message instead erroring out with a panic.
