### ISSUE TITLE
CLI panicking while doing cf app after app scale down.

### ISSUE THREAD

**Issue by savitaashture** [cloudfoundry/cli#408]
```
$ cf scale cf-env -i 50
Scaling app cf-env in org htipl / space testbed as admin...
OK
$ cf app cf-env
Showing health and status for app cf-env in org htipl / space testbed as admin...

OK

requested state: started
instances: 50/50
usage: 128M x 50 instances
urls: cf-env.10.244.0.34.xip.io
last uploaded: Thu Apr 9 11:37:21 UTC 2015
stack: lucid64

      state      since                    cpu    memory      disk      details
#0    running    2015-04-10 11:32:00 AM   0.0%   0 of 128M   0 of 1G
#1    running    2015-04-10 12:13:24 PM   0.0%   0 of 128M   0 of 1G
#2    running    2015-04-10 12:13:03 PM   0.0%   0 of 128M   0 of 1G
#3    running    2015-04-10 12:13:48 PM   0.0%   0 of 128M   0 of 1G
   --- removed unnecessary lines for brevity ---
#45   starting   2015-04-10 12:14:43 PM   0.0%   0 of 128M   0 of 1G
#46   starting   2015-04-10 12:14:43 PM   0.0%   0 of 128M   0 of 1G   insufficient resources
#47   starting   2015-04-10 12:14:43 PM   0.0%   0 of 128M   0 of 1G   insufficient resources
#48   starting   2015-04-10 12:14:43 PM   0.0%   0 of 128M   0 of 1G   insufficient resources
#49   starting   2015-04-10 12:14:43 PM   0.0%   0 of 128M   0 of 1G   insufficient resources
```
When we decrease the scale count 
We get this kind of Panic:
```
$ cf scale cf-env -i 40
Scaling app cf-env in org htipl / space testbed as admin...
OK
$ cf app cf-env
Showing health and status for app cf-env in org htipl / space testbed as admin...


        Aww shucks.

        Something completely unexpected happened. This is a bug in cf.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:

                cf app cf-env

        using this version of the CLI:

                BUILT_FROM_SOURCE

        and that this error occurred:

                runtime error: index out of range

        and this stack trace:

                goroutine 16 [running]:
        main.generateBacktrace(0x0, 0x0)
                /root/.gvm/pkgsets/go1.3.1/global/src/github.com/cloudfoundry/cli/main/main.go:177 +0xcf
        main.handlePanics(0x7f50db6c6a50, 0xc208045960)
                /root/.gvm/pkgsets/go1.3.1/global/src/github.com/cloudfoundry/cli/main/main.go:161 +0x15e
        runtime.panic(0xa45760, 0x1bf99bc)
                /root/.gvm/gos/go1.3.1/src/pkg/runtime/panic.c:248 +0x18d
        github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc208159310, 0xc20810dcb0, 0x24, 0xc208460000, 0x28, 0x28, 0x0, 0x0, 0x0, 0x0, ...)
                /root/.gvm/pkgsets/go1.3.1/global/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:65 +0x307
        github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc2081c4240, 0xc20810dcb0, 0x24, 0xc208187a38, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                /root/.gvm/pkgsets/go1.3.1/global/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:112 +0x7ea
        github.com/cloudfoundry/cli/c
```

**Comment by tjarratt** [comment]
Aww shucks. Thanks for filing this bug @savitaashture!

**Comment by goehmen** [comment]
This bug is scheduled to be addressed in the next sprint.
