### ISSUE TITLE
cli crashed when running `cf app`

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/cli#447]
```
$ CF_TRACE=true cf app grace

VERSION:
6.11.2-2a26d55


REQUEST: [2015-05-08T11:33:25-04:00]
GET /v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7/apps?q=name%3Agrace&inline-relations-depth=1 HTTP/1.1
Host: api.diego-2.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.11.2-2a26d55 / darwin



RESPONSE: [2015-05-08T11:33:25-04:00]
HTTP/1.1 200 OK
Content-Length: 4410
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Date: Fri, 08 May 2015 15:33:23 GMT
Server: nginx
X-Cf-Requestid: b70b5ad0-13c0-4fa7-5404-205b76a5f51d
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: dc52c82c-b9fb-46db-74b6-e17424f27bc0::9d3eeb94-d433-425e-99c7-222f82b38778

{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "991a6ce0-a332-41ce-b783-8f424f3d605d",
        "url": "/v2/apps/991a6ce0-a332-41ce-b783-8f424f3d605d",
        "created_at": "2015-05-07T22:42:04Z",
        "updated_at": "2015-05-08T15:30:07Z"
      },
      "entity": {
        "name": "grace",
        "production": false,
        "space_guid": "fe013e1d-bfbf-4620-84d1-a84160043ba7",
        "stack_guid": "ec416550-e87e-4c03-90f3-0b841c0c794d",
        "buildpack": null,
        "detected_buildpack": "Go",
        "environment_json": {

        },
        "memory": 10,
        "instances": 1,
        "disk_quota": 512,
        "state": "STARTED",
        "version": "95d55b15-d794-45f2-bdd1-0d836b6cefc1",
        "command": null,
        "console": false,
        "debug": null,
        "staging_task_id": "76f83b313e0b4704949d8004f141d0ed",
        "package_state": "STAGED",
        "health_check_type": "port",
        "health_check_timeout": null,
        "staging_failed_reason": null,
        "diego": true,
        "docker_image": null,
        "package_updated_at": "2015-05-07T22:42:16Z",
        "detected_start_command": "grace",
        "enable_ssh": false,
        "space_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7",
        "space": {
          "metadata": {
            "guid": "fe013e1d-bfbf-4620-84d1-a84160043ba7",
            "url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7",
            "created_at": "2015-05-07T18:26:31Z",
            "updated_at": null
          },
          "entity": {
            "name": "s",
            "organization_guid": "a0d82e79-8fb6-48ba-ae57-063474ececef",
            "space_quota_definition_guid": null,
            "allow_ssh": true,
            "organization_url": "/v2/organizations/a0d82e79-8fb6-48ba-ae57-063474ececef",
            "developers_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7/developers",
            "managers_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7/managers",
            "auditors_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7/auditors",
            "apps_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7/apps",
            "routes_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7/routes",
            "domains_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7/domains",
            "service_instances_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7/service_instances",
            "app_events_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7/app_events",
            "events_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7/events",
            "security_groups_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7/security_groups"
          }
        },
        "stack_url": "/v2/stacks/ec416550-e87e-4c03-90f3-0b841c0c794d",
        "stack": {
          "metadata": {
            "guid": "ec416550-e87e-4c03-90f3-0b841c0c794d",
            "url": "/v2/stacks/ec416550-e87e-4c03-90f3-0b841c0c794d",
            "created_at": "2015-05-07T18:23:05Z",
            "updated_at": null
          },
          "entity": {
            "name": "cflinuxfs2",
            "description": "Cloud Foundry Linux-based filesystem"
          }
        },
        "events_url": "/v2/apps/991a6ce0-a332-41ce-b783-8f424f3d605d/events",
        "service_bindings_url": "/v2/apps/991a6ce0-a332-41ce-b783-8f424f3d605d/service_bindings",
        "service_bindings": [

        ],
        "routes_url": "/v2/apps/991a6ce0-a332-41ce-b783-8f424f3d605d/routes",
        "routes": [
          {
            "metadata": {
              "guid": "767690b7-01ee-4fd4-a3f2-e3abf93a1d11",
              "url": "/v2/routes/767690b7-01ee-4fd4-a3f2-e3abf93a1d11",
              "created_at": "2015-05-07T18:26:42Z",
              "updated_at": null
            },
            "entity": {
              "host": "grace",
              "domain_guid": "32b9535b-c6d1-448b-b9d5-a5e43190fc7a",
              "space_guid": "fe013e1d-bfbf-4620-84d1-a84160043ba7",
              "path": "",
              "domain_url": "/v2/domains/32b9535b-c6d1-448b-b9d5-a5e43190fc7a",
              "space_url": "/v2/spaces/fe013e1d-bfbf-4620-84d1-a84160043ba7",
              "apps_url": "/v2/routes/767690b7-01ee-4fd4-a3f2-e3abf93a1d11/apps"
            }
          }
        ]
      }
    }
  ]
}
Showing health and status for app grace in org o / space s as admin...

REQUEST: [2015-05-08T11:33:25-04:00]
GET /v2/apps/991a6ce0-a332-41ce-b783-8f424f3d605d/summary HTTP/1.1
Host: api.diego-2.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.11.2-2a26d55 / darwin



RESPONSE: [2015-05-08T11:33:26-04:00]
HTTP/1.1 200 OK
Content-Length: 1003
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Date: Fri, 08 May 2015 15:33:24 GMT
Server: nginx
X-Cf-Requestid: cabfff14-c096-49c6-6888-bd2ef44bcd29
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 694ea034-c130-4052-7ba7-d373161a656a::7a17667d-babc-4cc6-9a9c-65a2679e2f1c

{"guid":"991a6ce0-a332-41ce-b783-8f424f3d605d","name":"grace","routes":[{"guid":"767690b7-01ee-4fd4-a3f2-e3abf93a1d11","host":"grace","domain":{"guid":"32b9535b-c6d1-448b-b9d5-a5e43190fc7a","name":"diego-2.cf-app.com"}}],"running_instances":1,"services":[],"available_domains":[{"guid":"32b9535b-c6d1-448b-b9d5-a5e43190fc7a","name":"diego-2.cf-app.com"}],"name":"grace","production":false,"space_guid":"fe013e1d-bfbf-4620-84d1-a84160043ba7","stack_guid":"ec416550-e87e-4c03-90f3-0b841c0c794d","buildpack":null,"detected_buildpack":"Go","environment_json":{},"memory":10,"instances":1,"disk_quota":512,"state":"STARTED","version":"95d55b15-d794-45f2-bdd1-0d836b6cefc1","command":null,"console":false,"debug":null,"staging_task_id":"76f83b313e0b4704949d8004f141d0ed","package_state":"STAGED","health_check_type":"port","health_check_timeout":null,"staging_failed_reason":null,"diego":true,"docker_image":null,"package_updated_at":"2015-05-07T22:42:16Z","detected_start_command":"grace","enable_ssh":false}

REQUEST: [2015-05-08T11:33:26-04:00]
GET /v2/apps/991a6ce0-a332-41ce-b783-8f424f3d605d/instances HTTP/1.1
Host: api.diego-2.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.11.2-2a26d55 / darwin



RESPONSE: [2015-05-08T11:33:26-04:00]
HTTP/1.1 200 OK
Content-Length: 44
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Date: Fri, 08 May 2015 15:33:24 GMT
Server: nginx
X-Cf-Requestid: 8b5aaae5-9223-4bdc-752c-bf976a407f6b
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: c57aa977-d728-482d-6b52-e2d57291d72d::c10f30e4-c5d0-4f14-b304-4caaf66de192

{"0":{"state":"RUNNING","since":1431094265}}

REQUEST: [2015-05-08T11:33:26-04:00]
GET /v2/apps/991a6ce0-a332-41ce-b783-8f424f3d605d/stats HTTP/1.1
Host: api.diego-2.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.11.2-2a26d55 / darwin



RESPONSE: [2015-05-08T11:33:26-04:00]
HTTP/1.1 200 OK
Content-Length: 114
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Date: Fri, 08 May 2015 15:33:25 GMT
Server: nginx
X-Cf-Requestid: 8971a961-f147-449c-6b46-5f93457d0bc2
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 8cbbdabd-0f07-4c2d-7854-b191391f18f6::67dbebe9-8d98-449e-8c84-b10e8c910373

{"0":{"state":"RUNNING","stats":{"mem_quota":10485760,"disk_quota":536870912,"usage":{"cpu":0,"mem":0,"disk":0}}}}


	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf app grace

	using this version of the CLI:

		6.11.2-2a26d55

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x109a5d8, 0xc210069540)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x564760, 0xe58c57)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc210250f60, 0xc2100cdea0, 0x24, 0xc210171e40, 0x1, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc210332240, 0xc2100cdea0, 0x24, 0xc21018a438, 0x5, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:112 +0x683
	github.com/c
```

**Comment by goehmen** [comment]
Looking into it.

**Comment by ematpl** [comment]
I've also run into this issue recently with 6.11.3. Can provide steps to reproduce with an app running on diego (basically, delete the app's DesiredLRP from Diego and then do `cf app` while it's missing).

Thanks,
Eric

**Comment by goehmen** [comment]
This will be fixed via https://www.pivotaltracker.com/story/show/95483596

**Comment by jberkhahn** [comment]
@ematpl Wrote a fix for this, should be in next time we cut a release.
