### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/cli#485]
```
± j+d |master ✓| → cf restart nora
Stopping app nora in org greenhouse / space greenhouse as admin...
OK

Starting app nora in org greenhouse / space greenhouse as admin...

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App nora was started using this command `tmp/lifecycle/WebAppServer.exe .`

Showing health and status for app nora in org greenhouse / space greenhouse as admin...


	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf restart nora

	using this version of the CLI:

		6.11.3-cebadc9

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x10c45d8, 0xc2100695a0)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x570540, 0xe7c917)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc2102663c0, 0xc210308ea0, 0x24, 0xc2102a76c0, 0x1, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc210266660, 0xc210308ea0, 0x24, 0xc21031b1b8, 0x4, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:112 +0x683
	github.com/c
```

**Comment by goehmen** [comment]
This bug was fixed in story https://www.pivotaltracker.com/story/show/95483596

That commit is in the latest edge binary and will be in the next stable release 6.12.0 which will get released in the next wee or two.

**Comment by benmoss** [comment]
Great, thank you, sorry I didn't spot that issue.

**Comment by goehmen** [comment]
yeah, no worries.

Greg Oehmen
Cloud Foundry Product Manager
415.205.6596
