### ISSUE TITLE
Exception running "cf app" and "cf start"

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/cli#515]
```
± d+s |master ✗| → cf start nora
Starting app nora in org diego / space diego as admin...

0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App nora was started using this command `tmp/lifecycle/WebAppServer.exe .`

Showing health and status for app nora in org diego / space diego as admin...


	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf start nora

	using this version of the CLI:

		6.12.1-56792aa

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:175 +0xa9
	main.handlePanics(0x116fef8, 0xc210187b80)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:159 +0x123
	runtime.panic(0x5a5b80, 0xf0d8b7)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc210269840, 0xc2108f96f0, 0x24, 0xc210269480, 0x1, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc21006c1c0, 0xc2108f96f0, 0x24, 0xc2108c3a48, 0x4, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x6e0
	github.com/c
```

```
± d+s |master ✗| → cf app nora
Showing health and status for app nora in org diego / space diego as admin...


	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf app nora

	using this version of the CLI:

		6.12.1-56792aa

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:175 +0xa9
	main.handlePanics(0x116faa0, 0xc21017fc60)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:159 +0x123
	runtime.panic(0x5a5b80, 0xf0d8b7)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc2102a4000, 0xc2102fb330, 0x24, 0xc210361f60, 0x1, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc21006e930, 0xc2102fb330, 0x24, 0xc2102d6368, 0x4, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x6e0
	github.com/c
```

**Comment by benmoss** [comment]
If it helps, I think we did this:
```
cf scale -i 4
cf scale -i 1
cf stop nora
cf start nora # => exception
cf app nora # => exception
```

**Comment by goehmen** [comment]
Hey @benmoss There is a bug in the CLI backlog that will help here.  Basically, you do not have yoru logging environment set up properly but the message you are getting back is not indicative of that issue.  We are addressing the situation the best we can on the CLI side by providing a more descriptive error message.

The bug is here:  https://www.pivotaltracker.com/story/show/98672332
