### ISSUE TITLE
index out of range while trying to scale an app

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry/cli#527]
Environment:

- bosh-lite
- release versions:
```
+-------+-----------------+-------------+
| Name  | Versions        | Commit Hash |
+-------+-----------------+-------------+
| cf    | 212+dev.1       | ea40d1b0    |
|       | 213+dev.1*      | b7becdf7+   |
| diego | 0.1392.0+dev.1  | 08470f1a+   |
|       | 0.1392.0+dev.2* | 08470f1a+   |
+-------+-----------------+-------------+
```
- logspew is a windows application (I'm a member of the greenhouse team)

Full terminal output:

```
$ cf scale -i 1 -m 1g logspew

This will cause the app to restart. Are you sure you want to scale logspew?> y

Scaling app logspew in org org / space space as admin...
OK
Stopping app logspew in org org / space space as admin...
OK

Starting app logspew in org org / space space as admin...

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App logspew was started using this command `tmp/lifecycle/WebAppServer.exe .`

Showing health and status for app logspew in org org / space space as admin...


	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf scale -i 1 -m 1g logspew

	using this version of the CLI:

		6.12.1-56792aa

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x7)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:175 +0xa9
	main.handlePanics(0x1170488, 0xc210188b80)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:159 +0x123
	runtime.panic(0x5a5b80, 0xf0d8b7)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc2102697e0, 0xc21009e960, 0x24, 0xc2102a5600, 0x1, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc21032e000, 0xc21009e960, 0x24, 0xc2100007a8, 0x7, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x6e0
	github.com/c
```

**Comment by goehmen** [comment]
This is a known bug.  basically, it is indicative of the fact that your env is not set up properly for logging.  See         /Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275

We are working on generating a more informative message in https://www.pivotaltracker.com/story/show/100130702 which is currently in progress
