### ISSUE TITLE
CLI panic when running cf space xxx --security-group-rules

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry/cli#531]
Happened on PWS. Ping me via email if you need the org name.

CLI version:
```
➜  ~  cf -v
cf version 6.12.2-24abed3-2015-07-15T21:21:22+00:00
```

CLI Panic:
```
➜  ~  cf space frodenas --security-group-rules
Getting info for space frodenas in org [REDACTED] as [REDACTED]...
OK

frodenas
           Org:               [REDACTED]
           Apps:              cf-env-frb
           Domains:           [REDACTED]
           Services:
           Security Groups:   public_networks, dns, ssh-logging, p-mysql, rdslogtologstash
           Space Quota:

Getting rules for the security group  : public_networks...

   destination   :   0.0.0.0-9.255.255.255
   protocol      :   all

   destination   :   11.0.0.0-169.253.255.255
   protocol      :   all

   destination   :   169.255.0.0-172.15.255.255
   protocol      :   all

   destination   :   172.32.0.0-192.167.255.255
   protocol      :   all

   destination   :   192.169.0.0-255.255.255.255
   protocol      :   all

Getting rules for the security group  : dns...

   destination   :   0.0.0.0/0
   ports         :   53
   protocol      :   tcp

   destination   :   0.0.0.0/0
   ports         :   53
   protocol      :   udp

Getting rules for the security group  : ssh-logging...


	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf space frodenas --security-group-rules

	using this version of the CLI:

		6.12.2-24abed3

	and that this error occurred:

		interface conversion: interface is bool, not string

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x4)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x116b418, 0xc210187600)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x5a8020, 0xc2103d9e80)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/commands/space.(*ShowSpace).Execute(0xc21026e1e0, 0x116c178, 0xc210265b80)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/space/space.go:135 +0x7bf
	main.main()
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:81 +0x9fb

	goroutine 4 [syscall]:
	os/signal.loop()
		/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
	created by os/signal.init·1
		/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x31

	goroutine 359 [IO wait]:
	n

```

**Comment by simonleung8** [comment]
Thanks for the report. We are able to reproduce and confirm the bug. The issue will be fixed and can be tracked here https://www.pivotaltracker.com/story/show/100469998

Closing this issue as we have the tracker story.
