### ISSUE TITLE
panic in create-app-manifest

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#536]
The cli panics when trying to save an app manifest while the app is stopped (and possibly old). Let me know if additional details could be useful.

```
C:\Users\Guillaume>cf create-app-manifest spring-travel
Creating an app manifest from current settings of app spring-travel ...



        Aww shucks.

        Something completely unexpected happened. This is a bug in cf.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:

                cf create-app-manifest spring-travel

        using this version of the CLI:

                6.12.2-24abed3

        and that this error occurred:

                runtime error: invalid memory address or nil pointer dereference

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xce
        main.handlePanics(0x149a60, 0xc0821e1a10)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x1ab
        github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc082176180, 0xc08224c300, 0x24, 0x
c0820d48a0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go
:91 +0x8c
        github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc082176180, 0x14a880, 0xc0821637c0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go
:87 +0x4d9
        main.main()
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:81 +0xcdd

        goroutine 360 [IO wait]:
        net.(*pollDesc).Wait(0xc0821aabf0, 0x72, 0x0, 0x0)
                c:/go/src/net/fd_poll_runtime.go:84 +0x4e
        net.(*ioSrv).E


```

**Comment by simonleung8** [comment]
Thanks for filing the bug, we have a story in the tracker and will be fixed in the next release.

https://www.pivotaltracker.com/story/show/101367528

**Comment by afeld** [comment]
https://github.com/cloudfoundry/cli/commit/43154bedb0ff54d69097a7a225abf6c6948cf3ce
