### ISSUE TITLE
`cf app` barfs 

### ISSUE THREAD

**Issue by phanle** [cloudfoundry/cli#543]
cf app dora

	using this version of the CLI:

		6.12.2-24abed3

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:
```
		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x116b9f0, 0xc210186560)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x5a3660, 0xf08d17)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc21026b960, 0xc2100c3210, 0x24, 0xc2104d37e0, 0x3, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc21006ea80, 0xc2100c3210, 0x24, 0xc21032f1b8, 0x4, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x6e0
	github.com/c
```

**Comment by phanle** [comment]
This is after I scaled down an app

**Comment by camelpunch** [comment]
We're removing the logs_noaa code on the next release. Should be fixed with that.
