### ISSUE TITLE
cf app APPNAME crashes with 100 instances

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry/cli#561]
use diego

scale an app to 100 instances

cf app has an index error

```
$ cf restart jbayer-lattice-app
Stopping app jbayer-lattice-app in org jbayer-org / space dev as jbayer@pivotal.io...
OK

Starting app jbayer-lattice-app in org jbayer-org / space dev as jbayer@pivotal.io...

0 of 100 instances running, 100 starting
2 of 100 instances running, 98 starting

App started


OK

App jbayer-lattice-app was started using this command `/lattice-app `

Showing health and status for app jbayer-lattice-app in org jbayer-org / space dev as jbayer@pivotal.io...


	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		/usr/local/bin/cf restart jbayer-lattice-app

	using this version of the CLI:

		6.12.2-4dbf534

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xc7
	main.handlePanics(0xe1b8d8, 0xc2080f2580)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x1a4
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc208218f60, 0xc2080c7ad0, 0x24, 0xc208a02000, 0x64, 0x64, 0x0, 0x0, 0x0, 0x0, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x2ea
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc2080117a0, 0xc2080c7ad0, 0x24, 0xc20842c280, 0x12, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x8e5
	github.com/cloudfoundry/cli/cf/commands/applicati
```

**Comment by goehmen** [comment]
known issue 

The issue is that NOAA is not set up correctly (see below). In 6.12.3, we will address this by providing a better error message than index out of range.
/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x2ea
