### ISSUE TITLE
Panic while downloading app manifest.

### ISSUE THREAD

**Issue by tsaleh** [cloudfoundry/cli#571]
```
$ cf create-app-manifest pivotal-cf-blog
Creating an app manifest from current settings of app pivotal-cf-blog ...



	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf create-app-manifest pivotal-cf-blog

	using this version of the CLI:

		6.12.3-c0c9a03

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xc7
	main.handlePanics(0x201b5c0, 0xc2080e6640)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x1a4
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc208212de0, 0xc208822e40, 0x24, 0xc20883e230, 0xf, 0xc208509f00, 0x38, 0x0, 0x0, 0x0, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:91 +0x85
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc208212de0, 0x201cf38, 0xc208177880)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:87 +0x4d2
	main.main()
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src
```

```
$ cf apps
Getting apps in org tammersaleh / space pivotal-cf-blog as tsaleh@pivotal.io...
OK

name              requested state   instances   memory   disk   urls
pivotal-cf-blog   started           1/1         64M      1G     pivotal-cf-blog.cfapps.io
```

```
$ cf app pivotal-cf-blog
Showing health and status for app pivotal-cf-blog in org tammersaleh / space pivotal-cf-blog as tsaleh@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 64M x 1 instances
urls: pivotal-cf-blog.cfapps.io
last uploaded: Sun Sep 6 10:23:58 UTC 2015
stack: cflinuxfs2
buildpack: https://github.com/cloudfoundry/staticfile-buildpack.git

     state     since                    cpu    memory      disk          details
#0   running   2015-09-06 11:24:12 AM   0.0%   6M of 64M   12.8M of 1G
```

**Comment by goehmen** [comment]
Thanks @tsaleh - this will be fixed in 6.12.4 - release marker in tracker https://www.pivotaltracker.com/story/show/102929152
