### ISSUE TITLE
Aww Shucks: runtime error: index out of range

### ISSUE THREAD

**Issue by weymanf** [cloudfoundry/cli#573]
```
Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:
```

command: `cf push -f lib/deploy/manifests/production-diego-manifest.yml`
CLI version: 6.12.2-24abed3
error: runtime error: index out of range

stacktrace 
```
goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x4)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x7f76ec87c9b0, 0xc210188460)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x9a2220, 0x1308177)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc210279780, 0xc210bb0b70, 0x24, 0xc210c45000, 0x5, ...)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc210047310, 0xc210bb0b70, 0x24, 0xc210505d80, 0xd, ...)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x6e

rake aborted!
Cf::CommandFailed: CF command has failed: push -f lib/deploy/manifests/production-diego-manifest.yml
```

We were pushing a diego app and this happened.

**Comment by goehmen** [comment]
Hi @weymanf - This is a known issue that was addressed in CLI v.6.12.3 which just released last week.  Please upgrade to latest stable CLI to resolve this issue.
