### ISSUE TITLE
Stack trace on redirect

### ISSUE THREAD

**Issue by MrEnzyme** [cloudfoundry/cli#579]
When the CLI gets redirected (from /uaa/login to /login, etc) it gives me a stack trace:
```
CF_TRACE=true cf f testapp

REQUEST: [2015-09-15T20:41:02Z]
GET /v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79/apps?q=name%3Atestapp&inline-relations-depth=1 HTTP/1.1
Host: localhost:8181
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.12.3-c0c9a03 / linux



RESPONSE: [2015-09-15T20:41:02Z]
HTTP/1.1 200 OK
Content-Length: 4616
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Date: Tue, 15 Sep 2015 20:41:02 GMT
Keep-Alive: timeout=20
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: ecb80cfe-884a-4c45-a726-b991e0f8f921

{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "4d9f1e9b-0f88-40c9-9814-f40422500c70",
        "url": "/v2/apps/4d9f1e9b-0f88-40c9-9814-f40422500c70",
        "created_at": "2015-09-15T16:38:35Z",
        "updated_at": "2015-09-15T20:29:54Z"
      },
      "entity": {
        "name": "testapp",
        "production": false,
        "space_guid": "ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79",
        "stack_guid": "60c16927-2a79-447f-a9ec-50ba51118478",
        "buildpack": "staticfile-buildpack",
        "detected_buildpack": null,
        "environment_json": {

        },
        "memory": 64,
        "instances": 2,
        "disk_quota": 1024,
        "state": "STARTED",
        "version": "9eed9b00-d3dc-412b-8295-c7122bff6c99",
        "command": null,
        "console": false,
        "debug": null,
        "staging_task_id": "44765997db4e4f6bb0adddab8c9b66be",
        "package_state": "STAGED",
        "health_check_type": "port",
        "health_check_timeout": null,
        "staging_failed_reason": null,
        "staging_failed_description": null,
        "diego": false,
        "docker_image": null,
        "package_updated_at": "2015-09-15T20:25:20Z",
        "detected_start_command": "sh boot.sh",
        "enable_ssh": null,
        "docker_credentials_json": {
          "redacted_message": "[PRIVATE DATA HIDDEN]"
        },
        "space_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79",
        "space": {
          "metadata": {
            "guid": "ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79",
            "url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79",
            "created_at": "2015-09-10T20:16:13Z",
            "updated_at": null
          },
          "entity": {
            "name": "app",
            "organization_guid": "a3480a85-74d2-4292-ba38-23888bdd03f7",
            "space_quota_definition_guid": null,
            "allow_ssh": true,
            "organization_url": "/v2/organizations/a3480a85-74d2-4292-ba38-23888bdd03f7",
            "developers_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79/developers",
            "managers_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79/managers",
            "auditors_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79/auditors",
            "apps_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79/apps",
            "routes_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79/routes",
            "domains_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79/domains",
            "service_instances_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79/service_instances",
            "app_events_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79/app_events",
            "events_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79/events",
            "security_groups_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79/security_groups"
          }
        },
        "stack_url": "/v2/stacks/60c16927-2a79-447f-a9ec-50ba51118478",
        "stack": {
          "metadata": {
            "guid": "60c16927-2a79-447f-a9ec-50ba51118478",
            "url": "/v2/stacks/60c16927-2a79-447f-a9ec-50ba51118478",
            "created_at": "2015-09-10T20:07:38Z",
            "updated_at": null
          },
          "entity": {
            "name": "cflinuxfs2",
            "description": "test cflinuxfs2 entry"
          }
        },
        "events_url": "/v2/apps/4d9f1e9b-0f88-40c9-9814-f40422500c70/events",
        "service_bindings_url": "/v2/apps/4d9f1e9b-0f88-40c9-9814-f40422500c70/service_bindings",
        "service_bindings": [

        ],
        "routes_url": "/v2/apps/4d9f1e9b-0f88-40c9-9814-f40422500c70/routes",
        "routes": [
          {
            "metadata": {
              "guid": "5737c5f5-b017-43da-9013-2b6fe7db03f7",
              "url": "/v2/routes/5737c5f5-b017-43da-9013-2b6fe7db03f7",
              "created_at": "2015-09-10T20:16:25Z",
              "updated_at": null
            },
            "entity": {
              "host": "testapp",
              "path": "",
              "domain_guid": "b7b11faf-6dab-4251-b124-c8fe7d49ffd5",
              "space_guid": "ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79",
              "service_instance_guid": null,
              "domain_url": "/v2/domains/b7b11faf-6dab-4251-b124-c8fe7d49ffd5",
              "space_url": "/v2/spaces/ef7445d0-2d2e-49a7-9a0a-dad0b0e34a79",
              "apps_url": "/v2/routes/5737c5f5-b017-43da-9013-2b6fe7db03f7/apps"
            }
          }
        ]
      }
    }
  ]
}
Getting files for app testapp in org wbx2 / space app as admin...

REQUEST: [2015-09-15T20:41:02Z]
GET /v2/apps/4d9f1e9b-0f88-40c9-9814-f40422500c70/instances/0/files// HTTP/1.1
Host: localhost:8181
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.12.3-c0c9a03 / linux




	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf f testapp

	using this version of the CLI:

		6.12.3-c0c9a03

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xa9
	main.handlePanics(0x7f6e03fc6638, 0xc210180580)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x123
	runtime.panic(0x980a00, 0x129f337)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/net.getBaseDomain(0xc210262e40, 0x56, 0x56, 0x8)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/http_client.go:100 +0x10c
	github.com/cloudfoundry/cli/cf/net.PrepareRedirect(0xc21026d000, 0xc2100bd330, 0x1, 0x1, 0x56, ...)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/http_client.go:36 +0x122
	net/http.(*Client).doFollowingRedirects(0xc21029d630, 0xc2102700d0, 0xb6d8f8, 0xc2102b2d
```

Is there something I'm doing to cause this?

**Comment by camelpunch** [comment]
Related to https://github.com/cloudfoundry/cli/issues/543?

**Comment by MrEnzyme** [comment]
I don't think it is, that one doesn't seem to be redirect related. Any redirect response code (like 302 Found) seems to cause this stack trace for me (whether via the CC or UAA)

**Comment by nicw** [comment]
@MrEnzyme apologies for the delay - are you still seeing this?

**Comment by dkoper** [comment]
Could you tell us more about your CF deployment? What is your API endpoint url as specified to `cf api` or `cf login -a`?
Your CF trace includes request header `Host: localhost:8181`. I would expect that to say something like `Host: api.<your-domain>`. I believe the panic occurs in code that tries to split up the domain into subdomains and that's failing as it contains no periods.

**Comment by MrEnzyme** [comment]
@dkoper that matches what I'm seeing, though it only happens on redirects. I was only seeing this on my test machine where I had all the CF components running in one place. On a real deployment where I gave a domain for the api target this doesn't happen.

**Comment by dkoper** [comment]
So if the uaa/login server is redirecting to localhost, there isn't much we can do on the CLI side.
I mean, we should display a proper message, but this environment sounds unique enough to assume no-one but you will ever see it.
May I suggest you check your deployment manifest or uaa/login configuration why it may be redirecting to localhost?

**Comment by MrEnzyme** [comment]
In this case I had built/run the components outside of bosh and was using custom config to test all the components together on a single vm, so I had things like the uaa endpoint set in the cloud controller config as localhost:8080/uaa. I didn't realize setting those addresses to localhost was such a nonstandard thing

**Comment by dkoper** [comment]
Me neither. It's good to have it documented here in this issue.
I'm going to close this issue as a won't-fix to allow the team to focus on other high priority issues. If your CF configuration turns out to be more common and we receive more issues about it, we can revisit and investigate deeper what is required to make this work. Fair?
(Alternatively, if you wish to submit a pull request, we will definitely take a look at it!)

Cheers,
* CLI team
