### ISSUE TITLE
cf create-app-manifest --> nil pointer

### ISSUE THREAD

**Issue by HeikoOsigus** [cloudfoundry/cli#601]
Try to create a app-manifest from a deployed and running app.
Tell us that you ran this command:

		cf create-app-manifest JavaRabbit

	using this version of the CLI:

		6.12.2-24abed3

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x7f9e9b52a868, 0xc210185570)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x9a2220, 0x1307f88)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc210276660, 0xc2101931e0, 0x24, 0xc21015d700, 0xa, ...)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:91 +0x57
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc210276660, 0x7f9e9b52b5c8, 0xc210270ec0)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:87 +0x4

**Comment by HeikoOsigus** [comment]
Checked command with CLI Version 6.12.4 --> works as expected.
So from my Point of view --> fixed with Version 6.12.4
