### ISSUE TITLE
Out of memory errors with `cf curl` and a with large response

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/cli#628]
When trying to use `cf curl` and there is a large response, cf uses a lot of memory and in some cases can run out.

Ex:  Using `cf curl` to download app bits.

```
tempest@tempest:~$ cf curl /v2/apps/86c18d4d-e40d-44f9-b20e-0a390b186883/download > app.zip 
fatal error: runtime: out of memory

goroutine 1 [running]: 
runtime.throw(0xe27137) 
/usr/local/go/src/pkg/runtime/panic.c:464 +0x69 fp=0x7f7ca6539630 
runtime.SysMap(0xc22eb20000, 0x2380000, 0xe37e18) 
/usr/local/go/src/pkg/runtime/mem_linux.c:131 +0xfe fp=0x7f7ca6539660 
runtime.MHeap_SysAlloc(0xe41d60, 0x2380000) 
/usr/local/go/src/pkg/runtime/malloc.goc:473 +0x10a fp=0x7f7ca65396a0 
MHeap_Grow(0xe41d60, 0x2380) 
/usr/local/go/src/pkg/runtime/mheap.c:241 +0x5d fp=0x7f7ca65396e0 
MHeap_AllocLocked(0xe41d60, 0x237a, 0xc200000000) 
/usr/local/go/src/pkg/runtime/mheap.c:126 +0x305 fp=0x7f7ca6539720 
runtime.MHeap_Alloc(0xe41d60, 0x237a, 0x100000000, 0x0) 
/usr/local/go/src/pkg/runtime/mheap.c:95 +0x7b fp=0x7f7ca6539748 
runtime.mallocgc(0x23793e6, 0x0, 0x9) 
/usr/local/go/src/pkg/runtime/malloc.goc:89 +0x484 fp=0x7f7ca65397b8 
gostringsize(0x7f7ca6539838, 0x23793e5) 
/usr/local/go/src/pkg/runtime/string.goc:50 +0x65 fp=0x7f7ca65397f0 
runtime.slicebytetostring(0xc22c75d000, 0x23793e5, 0x23793e5, 0x0, 0xc22a3e3000) 
/usr/local/go/src/pkg/runtime/string.goc:257 +0x31 fp=0x7f7ca6539820 
regexp.(*Regexp).ReplaceAllString(0xc2100766e0, 0xc22a3e3000, 0x23793e5, 0xc2100ed640, 0x1f, ...) 
/usr/local/go/src/pkg/regexp/regexp.go:438 +0x129 fp=0x7f7ca65398a8 
cf/net.func·002(0x8c9210, 0x5, 0xc22a3e3000, 0x23793e5, 0xc22a3e3000, ...) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/net/http_client.go:51 +0x21c fp=0x7f7ca6539948 
cf/net.Sanitize(0xc2105b6000, 0x23793e5, 0xc22a3e3000, 0x23793e5) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/net/http_client.go:61 +0x1c0 fp=0x7f7ca6539990 
cf/net.dumpResponse(0xc210060d80) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/net/http_client.go:86 +0x222 fp=0x7f7ca6539a50 
cf/net.Gateway.doRequest(0x7f7ca66bf9f8, 0xc21006e690, 0x98ba70, 0x1, 0x12a05f200, ...) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/net/gateway.go:391 +0xfb fp=0x7f7ca6539ae0 
cf/net.Gateway.doRequestAndHandlerError(0x7f7ca66bf9f8, 0xc21006e690, 0x98ba70, 0x1, 0x12a05f200, ...) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/net/gateway.go:365 +0x6f fp=0x7f7ca6539ba8 
cf/net.Gateway.doRequestHandlingAuth(0x7f7ca66bf9f8, 0xc21006e690, 0x98ba70, 0x1, 0x12a05f200, ...) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/net/gateway.go:336 +0x128 fp=0x7f7ca6539c60 
cf/net.Gateway.PerformRequest(0x7f7ca66bf9f8, 0xc21006e690, 0x98ba70, 0x1, 0x12a05f200, ...) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/net/gateway.go:209 +0x64 fp=0x7f7ca6539ce0 
cf/api.CloudControllerCurlRepository.Request(0x7f7ca66bf648, 0xc21006c450, 0x7f7ca66bf9f8, 0xc21006e690, 0x98ba70, ...) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/api/curl.go:45 +0x46d fp=0x7f7ca6539e48 
cf/api.(*CloudControllerCurlRepository).Request(0xc21006eee0, 0xc210000528, 0x3, 0x7fff141b68fa, 0x36, ...) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/api/app_events.go:1 +0x16f fp=0x7f7ca6539f28 
----- stack segment boundary ----- 
cf/commands.(*Curl).Run(0xc21006cbd0, 0xc210075d40) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/commands/curl.go:71 +0x245 fp=0xc210077290 
cf/command_runner.ConcreteRunner.RunCmdByName(0x7f7ca66c3b88, 0xc21006c9c0, 0x7f7ca66c3bb8, 0xc21007cc00, 0x8c2e70, ...) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/command_runner/runner.go:48 +0x32d fp=0xc210077350 
cf/command_runner.(*ConcreteRunner).RunCmdByName(0xc210056840, 0x8c2e70, 0x4, 0xc210075d40, 0x0, ...) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/command_runner/runner.go:1 +0xc6 fp=0xc2100773a0 
cf/app.func·002(0xc210075d40) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/cf/app/app.go:93 +0x4e fp=0xc2100773d8 
github.com/codegangsta/cli.Command.Run(0x8c2e70, 0x4, 0x0, 0x0, 0xc210057e80, ...) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/github.com/codegangsta/cli/command.go:73 +0x994 fp=0xc2100775f8 
github.com/codegangsta/cli.(*App).Run(0xc21006a210, 0xc21000a000, 0x3, 0x3, 0x80, ...) 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/github.com/codegangsta/cli/app.go:111 +0x855 fp=0xc210077798 
main.main() 
/home/ubuntu/jenkins-slave/workspace/go-cli-tests-linux-64/src/main/cf.go:62 +0x479 fp=0xc21007b7e8 
----- stack segment boundary ----- 
runtime.main() 
/usr/local/go/src/pkg/runtime/proc.c:220 +0x11f fp=0x7f7ca651ffa0 
runtime.goexit() 
/usr/local/go/src/pkg/runtime/proc.c:1394 fp=0x7f7ca651ffa8

goroutine 3 [syscall]: 
os/signal.loop() 
/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e 
created by os/signal.init·1 
/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 5 [syscall]: 
runtime.goexit() 
/usr/local/go/src/pkg/runtime/proc.c:1394

goroutine 6 [IO wait]: 
net.runtime_pollWait(0x7f7ca66c51b8, 0x72, 0x0) 
/usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a 
net.(*pollDesc).Wait(0xc2100d1920, 0x72, 0x7f7ca66bf270, 0xb) 
/usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34 
net.(*pollDesc).WaitRead(0xc2100d1920, 0xb, 0x7f7ca66bf270) 
/usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30 
net.(*netFD).Read(0xc2100d18c0, 0xc2100b7000, 0x8000, 0x8000, 0x0, ...) 
/usr/local/go/src/pkg/net/fd_unix.go:204 +0x2a0 
net.(*conn).Read(0xc210000640, 0xc2100b7000, 0x8000, 0x8000, 0x0, ...) 
/usr/local/go/src/pkg/net/net.go:122 +0xc5 
crypto/tls.(*block).readFromUntil(0xc210074f30, 0x7f7ca66c5310, 0xc210000640, 0x5, 0xc210000640, ...) 
/usr/local/go/src/pkg/crypto/tls/conn.go:459 +0xb6 
crypto/tls.(*Conn).readRecord(0xc2100d0780, 0x17, 0x0, 0x8) 
/usr/local/go/src/pkg/crypto/tls/conn.go:539 +0x107 
crypto/tls.(*Conn).Read(0xc2100d0780, 0xc2100f0000, 0x1000, 0x1000, 0x0, ...) 
/usr/local/go/src/pkg/crypto/tls/conn.go:897 +0x135 
bufio.(*Reader).fill(0xc2100d6ae0) 
/usr/local/go/src/pkg/bufio/bufio.go:91 +0x110 
bufio.(*Reader).Peek(0xc2100d6ae0, 0x1, 0x0, 0x0, 0x0, ...) 
/usr/local/go/src/pkg/bufio/bufio.go:119 +0xcb 
net/http.(*persistConn).readLoop(0xc210068800) 
/usr/local/go/src/pkg/net/http/transport.go:687 +0xb7 
created by net/http.(*Transport).dialConn 
/usr/local/go/src/pkg/net/http/transport.go:528 +0x607

goroutine 7 [select]: 
net/http.(*persistConn).writeLoop(0xc210068800) 
/usr/local/go/src/pkg/net/http/transport.go:791 +0x271 
created by net/http.(*Transport).dialConn 
/usr/local/go/src/pkg/net/http/transport.go:529 +0x61e
```

**Comment by dkoper** [comment]
Hi Dan,

Thank you for the bug report. I haven't tried to reproduce it but I assume that's easy enough.
I'll close this one and manage its priority in the tracker (link above).
Cheers!

* CLI team
