### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by poul-kg** [cloudfoundry/cli#661]
```
Aww shucks.

Something completely unexpected happened. This is a bug in cf.
Please file this bug : https://github.com/cloudfoundry/cli/issues
Tell us that you ran this command:

	/usr/bin/cf push

using this version of the CLI:

	6.12.4-b4b6af1

and that this error occurred:

	runtime error: invalid memory address or nil pointer dereference

and this stack trace:

	goroutine 1 [running]:
main.generateBacktrace(0xc21000a000, 0x2)
	/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xa9
main.handlePanics(0x7fa3c2814be0, 0xc2101832f0)
	/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x123
runtime.panic(0x992d00, 0x12cb4e8)
	/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0x7fa3c2815018, 0xc210194900, 0xb7c228, 0x1, 0x12a05f200, ...)
	/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:253 +0x245
github.com/cloudfoundry/cli/cf/net.Gateway.PerformPollingRequestForJSONResponse(0x7fa3c2815018, 0xc210194900, 0xb7c228, 0x1, 0x12a05f200, ...)
	/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:292 +0

```

**Comment by dkoper** [comment]
Hi,
Does this error happen continuously, on the latest cf cli version?
Does it happen only for this particular app, with a particular manifest and/or set of push options or any?
Can you rerun it with CF_TRACE=true and send us the trace output?

Cheers
* CLI team

**Comment by poul-kg** [comment]
The version I'm using is in output. I haven't updated it since that error.
This doesn't happens continuously, this if first time I noticed this error.
I'll rerun it with CF_TRACE in case this error happen more often.

**Comment by dkoper** [comment]
Okay, I'll close this issue for now. Feel free to reopen if you can reproduce it on the latest cf cli release and attach the trace log. Cheers.
