### ISSUE TITLE
"cf push" failing complaining of missing Java class

### ISSUE THREAD

**Issue by wildnez** [cloudfoundry/cli#725]
`cf push` on a .war file failing with the following stack trace:

```
2016-01-05T18:05:44.62+0530 [App/0]      ERR Caused by:
2016-01-05T18:05:44.62+0530 [App/0]      ERR java.lang.ClassNotFoundException: org.springframework.context.ApplicationContextInitializer
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.lang.ClassLoader.defineClass1(Native Method)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.security.AccessController.doPrivileged(Native Method)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:430)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.springframework.util.ClassUtils.forName(ClassUtils.java:260)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.springframework.web.context.ContextLoader.determineContextInitializerClasses(ContextLoader.java:438)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.springframework.web.context.ContextLoader.customizeContext(ContextLoader.java:471)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:388)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:294)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
2016-01-05T18:05:44.62+0530 [App/0]      ERR 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
2016-01-05T18:05:44.63+0530 [App/0]      ERR 	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
2016-01-05T18:05:44.63+0530 [App/0]      ERR 	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
2016-01-05T18:05:44.63+0530 [App/0]      ERR 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
2016-01-05T18:05:44.63+0530 [App/0]      ERR 	at Launcher.start(Launcher.java:67)
2016-01-05T18:05:44.64+0530 [App/0]      ERR 	at Launcher.main(Launcher.java:29)
```

This is a web app and can normally be deployed in any basic container such as Tomcat, Jetty etc.

**Comment by wildnez** [comment]
Here are Spring dependencies in my pom.xml - this also covers the missing class in question:
org.springframework.context.ApplicationContextInitializer

Versions:
        <spring.version>3.2.4.RELEASE</spring.version>
        <spring.security.version>3.1.4.RELEASE</spring.security.version>

Dependencies:
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-core</artifactId>
            <version>${spring.security.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-web</artifactId>
            <version>${spring.security.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-config</artifactId>
            <version>${spring.security.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-taglibs</artifactId>
            <version>${spring.security.version}</version>
        </dependency>

**Comment by nebhale** [comment]
What class/package is the `Launcher` class from?  I notice that you've got a large swathe of Jetty code in the stack so I'm guessing that's the issue.  If you're pushing WAR file (without a declared `Main-Class` in `META-INF/MANIFEST.MF`) we automatically run the application in Tomcat.  If you've got pieces of Jetty involved, it's unclear what would happen.

**Comment by wildnez** [comment]
Yes the app does use local Jetty container to run web app. I pushed a plain WAR without Main-class and it worked fine. I wonder why the platform complain about Jetty as all the dependencies were already bundled into WAR.

Except the curiosity above, we can close the ticket.
