### ISSUE TITLE
cf ssh not creating app from manifest

### ISSUE THREAD

**Issue by gemfarmer** [cloudfoundry/cli#727]
I am deploying [this](https://github.com/18F/dolores-landingham-bot) app on cloud foundry, and wanted to view the production console. 

I ran this command: `cf create-app-manifest dolores`

using this version of the CLI: `6.12.3-c0c9a03`

and this error occurred:

```runtime error: invalid memory address or nil pointer dereference```

and this stack trace:

```
goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xc7
	main.handlePanics(0xe1b270, 0xc208116700)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x1a4
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc208214c60, 0xc208817b90, 0x24, 0xc208829d16, 0x7, 0xc208501f80, 0x32, 0x0, 0x0, 0x0, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:91 +0x85
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc208214c60, 0xe1cbf0, 0xc20821cd80)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:87 +0x4d2
	main.main()
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/g
```

```2016/01/11 12:29:49 USAGE: cf-ssh -f manifest.yml```

Any clue what is going on?

**Comment by dkoper** [comment]
Hi @gemfarmer 
That's a known issue with that release. Please update your CLI.

Regards,
Dies Koper
CF CLI PM
