### ISSUE TITLE
cf update-service-broker fails with ArgumentError because of missing description

### ISSUE THREAD

**Issue by metmajer** [cloudfoundry/cli#816]
### Command

`cf update-service-broker docker-broker containers secret http://$brokerIP`

### CLI Version

6.16.1+924508c-2016-02-26

### Error

Updating service broker docker-broker as admin... FAILED Server error, status code: 502, error code: 10001, message: The service broker returned an invalid response for the request to http://$brokerIP/v2/catalog. Status Code: 500 Internal Server Error

Body:
Exceptions::ArgumentError in V2::CatalogsController#show
Missing Plan parameters: description

### Stack Trace

app/models/plan.rb:50:in `validate_attrs'
app/models/plan.rb:15:in `initialize'
app/models/plan.rb:11:in `new'
app/models/plan.rb:11:in `build'
app/models/service.rb:11:in `block in build'
app/models/service.rb:11:in `map'
app/models/service.rb:11:in `build'
app/models/catalog.rb:13:in `block in services'
app/models/catalog.rb:13:in `map'
app/models/catalog.rb:13:in `services'
app/controllers/v2/catalogs_controller.rb:5:in `show`

### CF Trace

REQUEST: [2016-04-13T20:16:07+02:00]
GET /v2/service_brokers?q=name%3Adocker-broker HTTP/1.1
Host: api.system.pcf.....com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.16.1+924508c / darwin

RESPONSE: [2016-04-13T20:16:07+02:00]
HTTP/1.1 200 OK
Content-Length: 522
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Date: Wed, 13 Apr 2016 18:16:05 GMT
Server: nginx
X-Cf-Requestid: d997522e-2ab1-41bd-4ef1-e4ddc564a6c7
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: e830f7ac-5118-4c43-76db-5ef940282401::5c826360-f253-48c5-8716-4b067fdbd41a

{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "0842ff97-4874-4362-8098-a82537aa36f1",
        "url": "/v2/service_brokers/0842ff97-4874-4362-8098-a82537aa36f1",
        "created_at": "2016-04-13T11:57:09Z",
        "updated_at": null
      },
      "entity": {
        "name": "docker-broker",
        "broker_url": "http://52.87.194.139",
        "auth_username": "containers",
        "space_guid": null
      }
    }
  ]
}
Updating service broker docker-broker as admin...

REQUEST: [2016-04-13T20:16:07+02:00]
PUT /v2/service_brokers/0842ff97-4874-4362-8098-a82537aa36f1 HTTP/1.1
Host: api.system.pcf.....com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.16.1+924508c / darwin

{"broker_url":"http://$brokerIP","auth_username":"containers","auth_password":"secret"}

RESPONSE: [2016-04-13T20:16:08+02:00]
HTTP/1.1 502 Bad Gateway
Content-Length: 105839
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Date: Wed, 13 Apr 2016 18:16:06 GMT
Server: nginx
X-Cf-Requestid: e076f14f-ba3e-4e48-55eb-70313b8add8a
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 52c0b94d-2bb8-4649-654d-09d3d73453f7::0cdb225f-0b15-4697-a557-6dd2e9f6223c

{
  "code": 10001,
  "description": "The service broker returned an invalid response for the request to http://$brokerIP/v2/catalog. Status Code: 500 Internal Server Error, Body: ...

### Platform Details

Mac OS X 10.10.5

### Shell

 iTerm

### Description

According to `cf update-service-broker -help`, there is no field 'description'. However the server response claims `Missing Plan parameters: description`.

**Comment by metmajer** [comment]
Figured out it was due to an incomplete configuration of `config/settings.yml` of the [cf-containers-broker](https://github.com/cloudfoundry-community/cf-containers-broker) project. While `cf create-service-broker` had succeeded, `cf update-service-broker` had required those missing settings.
