### ISSUE TITLE
Panic targeting CF API

### ISSUE THREAD

**Issue by zmb3** [cloudfoundry/cli#981]
- Command  
  `CF_TRACE=true cf api https://api.sys.sraod.layasinchana.com --skip-ssl-validation`
- What occurred, incl. error and/or stack trace

```
runtime error: index out of range

        Stack Trace
    goroutine 1 [running]:
    code.cloudfoundry.org/cli/utils/panichandler.generateBacktrace(0xc42000c2c0, 0x4)
        /Users/cffadmin/concourse-work-dir/containers/00001ln5sjn/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/utils/panichandler/handler.go:68 &#43;0x9d
    code.cloudfoundry.org/cli/utils/panichandler.HandlePanic()
        /Users/cffadmin/concourse-work-dir/containers/00001ln5sjn/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/utils/panichandler/handler.go:54 &#43;0x333
    panic(0x728600, 0xc420012160)
        /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 &#43;0x243
    code.cloudfoundry.org/cli/cf/net.getBaseDomain(0xc4205c4280, 0x78, 0x78, 0xc41ffc46ff)
        /Users/cffadmin/concourse-work-dir/containers/00001ln5sjn/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/net/http_client.go:106 &#43;0xf9
    code.cloudfoundry.org/cli/cf/net.(*client).checkRedirect(0xc42079e4c0, 0xc420772000, 0xc420156930, 0x1, 0x1, 0x4, 0x7fc7b1)
        /Users/cffadmin/concourse-work-dir/containers/00001ln5sjn/tmp/build/254d4083/gopath/src/code.c
```
- What you expected to occur
  Successfully target API endpiont 
- CLI Version  
  `cf version 6.22.1+6b7af9c-2016-09-24`
- CC API Endpoint Version  
  see `cf api` output
- CF Trace, if issue relates to HTTP requests or strange behavior  

```
REQUEST: [2016-10-19T09:05:45-04:00]
GET /v2/info HTTP/1.1
Host: api.sys.sraod.layasinchana.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.1+6b7af9c / darwin
```
- Platform & Shell Details  
  macOS 10.12
  iTerm2 w/ zsh

**Comment by zmb3** [comment]
This is only happening behind a client network and works fine otherwise, so they are probably just blocking something.

I'll leave this open in case you want to investigate whether this is a failure that we could handle better.

**Comment by XenoPhex** [comment]
Looks like there's a problem in the `getBaseDomain` function:
https://play.golang.org/p/DXLHR0Nd1v 
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x114bc0, 0x1040a010)
	/usr/local/go/src/runtime/panic.go:500 +0x720
main.getBaseDomain(0x128a13, 0x1e, 0x0, 0x0)
	/tmp/sandbox140045039/main.go:12 +0x180
main.main()
	/tmp/sandbox140045039/main.go:17 +0x40
```

**Comment by zmb3** [comment]
Yeah, `url.Parse` really shouldn't be used if there's no scheme.

**Comment by XenoPhex** [comment]
can you run the following command and give us the output?
```
curl -vv https://api.sys.sraod.layasinchana.com/v2/info
```
NOTE: This is a standard `curl` not a `cf curl`

**Comment by zmb3** [comment]
On my home network I get the following:
```
❯ curl -vv -L -k https://api.sys.sraod.layasinchana.com/v2/info
*   Trying 52.1.138.222...
* Connected to api.sys.sraod.layasinchana.com (52.1.138.222) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.pcfsolutions.com
> GET /v2/info HTTP/1.1
> Host: api.sys.sraod.layasinchana.com
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json;charset=utf-8
< Date: Fri, 21 Oct 2016 22:59:50 GMT
< Server: nginx
< X-Content-Type-Options: nosniff
< X-Vcap-Request-Id: cfd7792a-01ed-4eb7-7bea-6bca8ae68c61
< X-Vcap-Request-Id: cfd7792a-01ed-4eb7-7bea-6bca8ae68c61::7dd293e8-dcb6-4e95-8bf4-9b170f5fb88f
< Content-Length: 689
< Connection: keep-alive
<
* Connection #0 to host api.sys.sraod.layasinchana.com left intact
{"name":"","build":"","support":"https://support.pivotal.io","version":0,"description":"","authorization_endpoint":"https://login.sys.sraod.layasinchana.com","token_endpoint":"https://uaa.sys.sraod.layasinchana.com","min_cli_version":"6.7.0","min_recommended_cli_version":"6.11.2","api_version":"2.58.0","app_ssh_endpoint":"ssh.sys.sraod.layasinchana.com:2222","app_ssh_host_key_fingerprint":"0b:fb:ff:33:9d:4a:aa:ea:54:40:58:e4:50:13:63:6c","app_ssh_oauth_client":"ssh-proxy","routing_endpoint":"https://api.sys.sraod.layasinchana.com/routing","logging_endpoint":"wss://loggregator.sys.sraod.layasinchana.com:443","doppler_logging_endpoint":"wss://doppler.sys.sraod.layasinchana.com:443"}
```

I can repeat the experiment on the customer network where the error occurred next week.

**Comment by XenoPhex** [comment]
@zmb3 Is this still a problem with the latest version of the CF CLI?

**Comment by zmb3** [comment]
Hard to say. I no longer have access to the environment that was experiencing the problem.

**Comment by XenoPhex** [comment]
Thanks for the quick response, I'll talk with my PM to figure out how we want to proceed. But considering we've re-written this command from scratch (after this ticket was filed), we might just close this ticket.

Sorry we couldn't get to the core of the issue. The new code no longer uses the `getBaseDomain` functionality, so hopefully it works now.

**Comment by zmb3** [comment]
I think closing this is fine. I'll be sure to let you know if it happens
again 😀
